import { useEffect, useMemo, useState } from 'react'
import SEO from '../../components/ui/SEO'
import Breadcrumbs from '../../components/ui/Breadcrumbs'

const PACKS={
  easy:{label:'🟢 קל',categories:['שם','חיה','מאכל','צבע','עיר'],letters:'אבגדהולמנסקת'},
  classic:{label:'🟡 קלאסי',categories:['שם','עיר','מדינה','חיה','צומח','דומם','מאכל','מקצוע'],letters:'אבגדהוזחיכלמנסעתקר'},
  party:{label:'🎉 מסיבה',categories:['שם של אורח','שיר','מאכל','מתנה','משחק','דבר מצחיק','סרט','חפץ בבית'],letters:'אבגדהולמנסקת'},
  funny:{label:'😂 מצחיק',categories:['תירוץ','כוח על','שם ללהקה','דבר מביך','מקצוע מומצא','שם לחיית מחמד','כותרת לסרט','חוק חדש'],letters:'אבגדהולמנסקת'},
  custom:{label:'✏️ מותאם אישית',categories:['שם','עיר','חיה'],letters:'אבגדהוזחיכלמנסעתקר'},
}
function randomLetter(pack){const letters=PACKS[pack].letters;return letters[Math.floor(Math.random()*letters.length)]}
export default function EretzIr(){
 const [pack,setPack]=useState('classic'),[customCategories,setCustomCategories]=useState(['שם','עיר','חיה']),[newCategory,setNewCategory]=useState(''),[letter,setLetter]=useState('מ'),[seconds,setSeconds]=useState(90),[running,setRunning]=useState(false),[round,setRound]=useState(1),[scores,setScores]=useState([{name:'קבוצה א׳',score:0},{name:'קבוצה ב׳',score:0}])
 const categories=pack==='custom'?customCategories:PACKS[pack].categories
 const [answers,setAnswers]=useState({})
 useEffect(()=>{if(!running||seconds===0)return;const t=setTimeout(()=>setSeconds(s=>s-1),1000);return()=>clearTimeout(t)},[running,seconds])
 const start=()=>{setLetter(randomLetter(pack));setSeconds(90);setAnswers({});setRunning(true)}
 const finish=()=>setRunning(false)
 const nextRound=()=>{setRound(r=>r+1);start()}
 const score=(index,delta)=>setScores(s=>s.map((x,i)=>i===index?{...x,score:Math.max(0,x.score+delta)}:x))
 const activeCount=Object.values(answers).filter(Boolean).length
 return <div className="mx-auto max-w-6xl px-4 py-8"><SEO title="ארץ־עיר BUGA" description="ארץ־עיר דיגיטלי עם אות אקראית, קטגוריות, טיימר וניקוד קבוצות." path="/tools/eretz-ir"/><Breadcrumbs items={[{label:'ראשי',href:'/'},{label:'משחקים',href:'/games'},{label:'ארץ־עיר'}]}/><header className="text-center mb-7"><h1 className="text-4xl sm:text-5xl">🗺️ ארץ־עיר BUGA</h1><p className="mt-2 text-lg text-[var(--muted-foreground)]">אות, קטגוריות, טיימר וניקוד — משחקים מיד על אותו מסך.</p></header><section className="grid gap-5 lg:grid-cols-[280px_1fr]">
 <aside className="order-2 space-y-4 lg:order-1"><div className="rounded-3xl border border-[var(--border)] bg-white p-5"><h2 className="text-2xl mb-3">בחרו חבילה</h2>{Object.entries(PACKS).map(([id,item])=><button key={id} onClick={()=>{setPack(id);setRunning(false);setAnswers({});setSeconds(90)}} className={`mb-2 block w-full rounded-xl border p-3 text-right font-bold ${pack===id?'bg-purple-100 border-purple-500':'bg-white'}`}>{item.label}<small className="block text-[var(--muted-foreground)]">{item.categories.length} קטגוריות</small></button>)}</div><div className="rounded-3xl border border-[var(--border)] bg-white p-5"><h2 className="text-2xl mb-3">ניקוד קבוצות</h2>{scores.map((team,index)=><div key={index} className="mb-3 rounded-xl bg-slate-50 p-3"><input value={team.name} onChange={e=>setScores(s=>s.map((x,i)=>i===index?{...x,name:e.target.value}:x))} className="w-full bg-transparent font-bold outline-none"/><div className="mt-2 flex items-center justify-between"><button onClick={()=>score(index,-5)}>−5</button><strong className="text-2xl">{team.score}</strong><button onClick={()=>score(index,5)}>+5</button></div></div>)}<p className="text-sm text-[var(--muted-foreground)]">10 נק׳ לתשובה ייחודית, 5 לתשובה שחוזרת אצל קבוצה אחרת.</p></div></aside>
 <main className="order-1 rounded-[32px] border border-[var(--border)] bg-white p-5 sm:p-8 shadow-[0_10px_30px_rgb(25_36_75_/_8%)] lg:order-2"><div className="flex flex-wrap items-center justify-between gap-4"><div><p className="text-sm text-[var(--muted-foreground)]">סיבוב {round}</p><h2 className="text-2xl">האות שנבחרה</h2></div><div className="grid h-28 w-28 place-items-center rounded-full bg-gradient-to-br from-cyan-100 to-violet-100 text-7xl font-bold text-violet-700">{letter}</div><div className={`text-3xl font-bold ${seconds<15?'text-red-500':'text-slate-800'}`}>⏱ {Math.floor(seconds/60)}:{String(seconds%60).padStart(2,'0')}</div></div><div className="my-6 flex flex-wrap justify-center gap-3">{!running?<button onClick={start} className="rounded-2xl bg-violet-600 px-7 py-4 text-xl font-bold text-white">{activeCount?'סיבוב חדש':'מגרילים אות ומתחילים'} 🎲</button>:<button onClick={finish} className="rounded-2xl bg-red-500 px-7 py-4 text-xl font-bold text-white">BUGA! עצרו את הזמן</button>}{!running&&activeCount>0&&<button onClick={nextRound} className="rounded-2xl border px-6 py-4 font-bold">הסיבוב הבא ←</button>}</div><div className="grid gap-3 sm:grid-cols-2">{categories.map(category=><label key={category} className="rounded-2xl border border-slate-200 bg-slate-50 p-4"><span className="mb-2 block font-bold">{category} באות {letter}</span><input disabled={!running} value={answers[category]||''} onChange={e=>setAnswers(a=>({...a,[category]:e.target.value}))} placeholder={running?'כותבים תשובה...':'התחילו סיבוב כדי לכתוב'} className="w-full rounded-xl border bg-white px-3 py-2 outline-none focus:ring-2 focus:ring-violet-300"/></label>)}</div><div className="mt-6 rounded-2xl bg-violet-50 p-4 text-center"><strong>{activeCount}/{categories.length} קטגוריות מולאו</strong><p className="mt-1 text-sm text-[var(--muted-foreground)]">בסיום משווים תשובות: ייחודית 10, תשובה שחוזרת 5, ריק 0. המנחה מעדכן ניקוד בצד.</p></div></main></section></div>
}
