import { useState } from 'react'
import SEO from '../../components/ui/SEO'
import Breadcrumbs from '../../components/ui/Breadcrumbs'

const EXPERIMENTS=[
 {id:'pepper',title:'פלפל בורח מהסבון',topic:'מים',age:'כיתות א–ג',question:'מה קורה למתח הפנים של המים כשמוסיפים סבון?',equipment:'צלחת, מים, פלפל שחור, סבון כלים',steps:['מלאו צלחת במים.','פזרו פלפל שחור על פני המים.','טבלו אצבע בסבון ונגעו במרכז המים.'],result:'הפלפל מתרחק במהירות מהנקודה שבה נגע הסבון.',source:'מכון דוידסון — מדע בבית'},
 {id:'rainbow',title:'קשת בכוס',topic:'אור',age:'כיתות ב–ו',question:'איך אפשר לפרק אור לבן לצבעים?',equipment:'כוס מים שקופה, דף לבן, אור שמש',steps:['הניחו את הכוס ליד חלון מואר.','הציבו דף לבן מאחוריה.','שנו מעט את הזווית עד שמופיעים צבעים.'],result:'האור נשבר במים ונפרד לצבעים שונים.',source:'מכון דוידסון — מדע בבית'},
 {id:'paper-bridge',title:'גשר מנייר',topic:'הנדסה',age:'כיתות א–ו',question:'איזו צורת קיפול תיצור גשר חזק יותר?',equipment:'דפי נייר, שתי כוסות, מטבעות',steps:['הניחו שתי כוסות במרחק קבוע.','הניחו דף שטוח ביניהן ובדקו כמה מטבעות הוא מחזיק.','קפלו דף בצורת אקורדיון ובדקו שוב.'],result:'קיפולים משנים את פיזור העומס ומחזקים את הנייר.',source:'משרד החינוך — חקר מדעי'},
 {id:'seed',title:'מה צריך זרע?',topic:'צמחים',age:'גן–כיתה ד׳',question:'האם זרע יכול לנבוט בלי אור או מים?',equipment:'שלוש כוסות, צמר גפן, עדשים או שעועית, מים',steps:['הניחו זרעים בשלוש כוסות.','השקו כוס אחת, השאירו אחת יבשה והניחו אחת בחושך.','בדקו מדי יום במשך שבוע.'],result:'מים חיוניים לנביטה; לאחר מכן גם אור משפיע על התפתחות הצמח.',source:'משרד החינוך — מדע וטכנולוגיה'},
]
export default function ExperimentMaker(){const [id,setId]=useState(EXPERIMENTS[0].id),[notes,setNotes]=useState({}),exp=EXPERIMENTS.find(x=>x.id===id);return <div className="mx-auto max-w-6xl px-4 py-8"><SEO title="מעבדת BUGA — מחולל ניסויים לכיתה" description="ניסויים מדעיים בטוחים עם דף חקר למילוי ולהדפסה." path="/tools/experiment-maker"/><Breadcrumbs items={[{label:'ראשי',href:'/'},{label:'לכיתה',href:'/classroom'},{label:'מעבדת BUGA'}]}/><header className="text-center"><div className="text-6xl">🔬</div><h1 className="mt-3 text-4xl font-black sm:text-6xl">מעבדת BUGA</h1><p className="mt-2 text-xl text-slate-600">בוחרים ניסוי, חוקרים, כותבים ומדפיסים.</p></header><div className="no-print mx-auto mt-8 flex max-w-4xl flex-wrap justify-center gap-2">{EXPERIMENTS.map(x=><button key={x.id} onClick={()=>setId(x.id)} className={`rounded-2xl border-2 px-4 py-3 font-bold ${id===x.id?'border-violet-500 bg-violet-100':'bg-white'}`}>{x.title}</button>)}</div><article className="mx-auto mt-8 max-w-4xl rounded-3xl border-2 border-slate-800 bg-white p-6 shadow-[0_7px_0_#172033] sm:p-10"><div className="flex flex-wrap justify-between gap-4 border-b-2 border-dashed pb-5"><div><span className="rounded-full bg-violet-100 px-3 py-1 font-bold">{exp.topic}</span><h2 className="mt-3 text-3xl font-black">{exp.title}</h2><p className="text-slate-600">מתאים ל־{exp.age}</p></div><div className="text-5xl">🧪</div></div><section className="mt-6 grid gap-5 md:grid-cols-2"><div><h3 className="text-xl font-black">שאלת החקר</h3><p className="mt-1 text-lg">{exp.question}</p><h3 className="mt-5 text-xl font-black">ציוד</h3><p className="mt-1">{exp.equipment}</p></div><div><h3 className="text-xl font-black">שלבי הניסוי</h3><ol className="mt-2 list-decimal space-y-2 pr-6">{exp.steps.map(s=><li key={s}>{s}</li>)}</ol></div></section><section className="mt-6 grid gap-4 md:grid-cols-2"><label className="font-bold">ההשערה שלי<textarea value={notes.hypothesis||''} onChange={e=>setNotes(n=>({...n,hypothesis:e.target.value}))} className="mt-1 h-24 w-full rounded-xl border-2 p-3" placeholder="אני חושב/ת ש..."/></label><label className="font-bold">מה גיליתי?<textarea value={notes.discovery||''} onChange={e=>setNotes(n=>({...n,discovery:e.target.value}))} className="mt-1 h-24 w-full rounded-xl border-2 p-3" placeholder="ראיתי ש..."/></label></section><div className="mt-5 rounded-2xl bg-amber-50 p-4"><b>תוצאה צפויה:</b> {exp.result}</div><p className="mt-5 text-sm text-slate-500">מקור: {exp.source}. יש לבצע בהשגחת מבוגר ולפעול לפי כללי בטיחות.</p><div className="no-print mt-6 text-center"><button onClick={()=>window.print()} className="rounded-2xl bg-violet-600 px-7 py-3 font-bold text-white">🖨️ הדפסת דף החקר</button></div></article><style>{`@media print{.no-print,header.site-header,footer{display:none!important}article{box-shadow:none!important;border:0!important}}`}</style></div>}
