import { useMemo, useRef, useState } from 'react'
import { Link } from 'react-router-dom'
import SEO from '../../components/ui/SEO'
import Breadcrumbs from '../../components/ui/Breadcrumbs'
import { crossword, normalize, wordSearch, sudoku, random } from '../../data/puzzleEngine'
import { PACKS, SENTENCES } from '../../data/puzzlePacks'
import './PuzzleStudio.css'

const TYPES=[['crossword','תשבץ','מילים מצטלבות','🧩'],['search','תפזורת','מחפשים מילים','🔎'],['sudoku','סודוקו','חושבים במספרים','🔢'],['fill','השלמת משפטים','מוצאים את המילה','✍️'],['numbers','ריבועי חשבון','משלימים סכומים','➕']]
const DIRECTIONS={across:'מאוזן',down:'מאונך'}
const customDefault=PACKS.nature.words.map(([w,c])=>`${w} | ${c}`).join('\n')
// Each browser visit starts with a different puzzle. The explicit "new puzzle"
// button advances the same seed, so it also cannot repeat the initial board.
const freshSeed=()=>Math.floor(Math.random()*2147483647)

export default function PuzzleStudio(){
  const [type,setType]=useState('crossword'),[pack,setPack]=useState('nature'),[seed,setSeed]=useState(freshSeed),[level,setLevel]=useState('easy')
  const [editing,setEditing]=useState(false),[draft,setDraft]=useState(customDefault),[custom,setCustom]=useState(null),[error,setError]=useState('')
  const entries=custom||PACKS[pack].words
  function changeType(id){setType(id);setEditing(false);setError('');setCustom(null)}
  function create(){const rows=draft.trim().split('\n').filter(x=>x.trim()).map(row=>row.split('|').map(x=>x.trim()));
    if(rows.length<3||rows.length>24){setError('הכניסו בין 3 ל־24 שורות.');return}
    if(type==='fill'){
      if(rows.some(([sentence,answer])=>!sentence?.includes('___')||!answer)){setError('בכל שורה כתבו משפט עם ___ ואז | והתשובה.');return}
    }else if(rows.some(([word,clue])=>!word||! /^[א-ת\s־-]+$/.test(word)||normalize(word).length<2||normalize(word).length>12||(type==='crossword'&&!clue))){setError('כתבו מילים בעברית באורך 2–12 אותיות, ולכל מילת תשבץ הוסיפו רמז אחרי |.');return}
    if(new Set(rows.map(x=>normalize(x[0]))).size!==rows.length){setError('יש שורות כפולות. השאירו כל מילה או משפט פעם אחת.');return}
    if(type==='crossword'&&crossword(rows,seed).placed.length<2){setError('המילים אינן מצטלבות. הוסיפו מילים שיש ביניהן אותיות משותפות.');return}
    setCustom(rows);setEditing(false);setError('');setSeed(s=>s+1)
  }
  return <div className="puzzle-studio" dir="rtl">
    <SEO title="תשבצים, תפזורות וסודוקו בעברית" description="פתרו תשבצים עם רמזים למאוזן ולמאונך, חפשו מילים בתפזורת ושחקו סודוקו. בנו תשבץ אישי והדפיסו דף פעילות." path="/tools/crossword-maker"/>
    <div className="no-print"><Breadcrumbs items={[{label:'ראשי',href:'/'},{label:'יוצרים',href:'/create'},{label:'תשבצים וחידות'}]}/></div>
    <header className="puzzle-heading no-print"><div><span className="puzzle-eyebrow">זמן קטן לאתגר גדול</span><h1>תשבצים וחידות</h1><p>בוחרים חידה, חושבים קצת — ונהנים מכל פתרון.</p></div><span className="puzzle-heading-icon" aria-hidden="true">🧩</span></header>
    <nav className="puzzle-types no-print" aria-label="סוג החידה">{TYPES.map(([id,title,sub,icon])=><button key={id} aria-pressed={type===id} onClick={()=>changeType(id)}><span aria-hidden="true">{icon}</span><b>{title}</b><small>{sub}</small></button>)}</nav>
    <div className="puzzle-controls no-print">
      {['crossword','search'].includes(type)&&<label>נושא<select value={custom?'custom':pack} onChange={e=>{setPack(e.target.value);setCustom(null)}}>{Object.entries(PACKS).map(([id,p])=><option key={id} value={id}>{p.icon} {p.label}</option>)}{custom&&<option value="custom">החידה שלי</option>}</select></label>}
      {['sudoku','search'].includes(type)&&<label>{type==='sudoku'?'גודל הלוח':'כיווני החיפוש'}<select value={level} onChange={e=>setLevel(e.target.value)}><option value="easy">{type==='sudoku'?'4 × 4 · מתחילים':'מאוזן ומאונך'}</option><option value="hard">{type==='sudoku'?'9 × 9 · רגיל':'גם באלכסון'}</option></select></label>}
      <button className="puzzle-new-button" onClick={()=>setSeed(s=>s+1)} title="החליפו לשאלות ולתשובות חדשות">↻ חידה חדשה</button>
      {['crossword','search','fill'].includes(type)&&<button aria-expanded={editing} onClick={()=>{setDraft(type==='fill'?SENTENCES.map(([s,a])=>`${s} | ${a}`).join('\n'):entries.map(([w,c])=>`${w} | ${c}`).join('\n'));setEditing(x=>!x);setError('')}}>✎ {type==='search'?'בנו תפזורת משלכם':type==='fill'?'בנו משפטים משלכם':'בנו תשבץ משלכם'}</button>}
    </div>
    {editing&&<section className="puzzle-builder no-print"><h2>{type==='search'?'התפזורת שלכם':type==='fill'?'המשפטים שלכם':'התשבץ שלכם'}</h2><label htmlFor="puzzle-draft">{type==='fill'?'כל שורה: משפט עם ___ | המילה החסרה':type==='search'?'כל שורה: מילה (אפשר להוסיף | רמז, אך הוא לא חובה)':'כל שורה: מילה | רמז למילה'}</label><textarea id="puzzle-draft" rows={8} value={draft} onChange={e=>setDraft(e.target.value)}/><p>בין 3 ל־24 שורות. אפשר להחליף את הדוגמאות במילים שלכם. לאחר היצירה הכפתור „חידה חדשה” יגריל לוח חדש מאותה רשימה.</p>{error&&<p role="alert">{error}</p>}<button className="puzzle-primary" onClick={create}>צרו את החידה</button></section>}
    <section className="puzzle-paper" key={`${type}-${pack}-${seed}-${level}-${JSON.stringify(custom)}`}>
      {type==='crossword'?<Crossword entries={entries} seed={seed} title={custom?'התשבץ שלי':`תשבץ ${PACKS[pack].label}`}/>:type==='search'?<SearchGame entries={entries} seed={seed} diagonal={level==='hard'} custom={custom}/>:type==='sudoku'?<SudokuGame seed={seed} n={level==='hard'?9:4}/>:type==='fill'?<FillGame seed={seed} custom={custom}/>:<NumberGame seed={seed}/>}
    </section>
    <p className="puzzle-footnote no-print">אפשר לפתור כאן או להדפיס ולמלא בעיפרון. <Link to="/printables">לכל דפי ההדפסה ←</Link></p>
  </div>
}

function Actions({check,reset,message,success}){return <div className="puzzle-actions no-print"><div><button className="puzzle-primary" onClick={check}>בדקו תשובות</button><button onClick={()=>window.print()}>הדפסה</button><button onClick={()=>{if(window.confirm('למחוק את התשובות בחידה הזאת?'))reset()}}>ניקוי תשובות</button></div><p role="status" className={success?'puzzle-success':''}>{message||'אפשר לטעות, למחוק ולנסות שוב.'}</p></div>}

function Crossword({entries,seed,title}){
  const puzzle=useMemo(()=>crossword(entries,seed),[entries,seed]),[answers,setAnswers]=useState({}),[selected,setSelected]=useState(0),[checked,setChecked]=useState(false),refs=useRef({})
  const active=puzzle.placed[selected],correct=puzzle.cells.filter(c=>c.letter&&normalize(answers[c.key]||'')===c.letter).length,total=puzzle.cells.filter(c=>c.letter).length,solved=correct===total
  function choose(index,focus=true){setSelected(index);if(focus)refs.current[puzzle.placed[index].keys[0]]?.focus()}
  function move(key,delta){const i=active.keys.indexOf(key);if(i>=0&&active.keys[i+delta])refs.current[active.keys[i+delta]]?.focus()}
  function selectCell(key,toggle=false){const indices=puzzle.placed.map((p,i)=>p.keys.includes(key)?i:-1).filter(i=>i>=0);if(!indices.includes(selected))setSelected(indices[0]);else if(toggle&&indices.length===2)setSelected(indices.find(i=>i!==selected))}
  return <><div className="puzzle-paper-title"><div><small>תשבץ עברי · {puzzle.placed.length} הגדרות</small><h2>{title}</h2></div><span className="no-print">{Object.values(answers).filter(Boolean).length} / {total} אותיות</span></div>
    {puzzle.omitted.length>0&&<p className="puzzle-note no-print">המילים שלא השתלבו בלוח: {puzzle.omitted.join('، ')}. אפשר לערוך את הרשימה או ליצור חידה חדשה.</p>}
    <div className="crossword-workspace"><div className="puzzle-board-side"><div className="active-clue no-print"><b>{active.number}. {DIRECTIONS[active.d]} {active.d==='across'?'←':'↓'}</b><span>{active.clue} ({active.word.length})</span><div><button aria-label="הרמז הקודם" onClick={()=>choose((selected+puzzle.placed.length-1)%puzzle.placed.length)}>→</button><button aria-label="הרמז הבא" onClick={()=>choose((selected+1)%puzzle.placed.length)}>←</button></div></div>
<div className="puzzle-board-scroll"><div className="real-crossword" style={{gridTemplateColumns:`repeat(${puzzle.cols},minmax(0,1fr))`}}>{puzzle.cells.map(cell=>!cell.letter?<div key={cell.key} className="crossword-black" aria-hidden="true"/>:<div key={cell.key} className={`crossword-white ${active.keys.includes(cell.key)?'word-active':''} ${checked&&answers[cell.key]?(normalize(answers[cell.key])===cell.letter?'cell-correct':'cell-wrong'):''}`}><span>{cell.number}</span><input ref={el=>{refs.current[cell.key]=el}} aria-label={`שורה ${cell.r+1}, עמודה ${cell.c+1}${cell.number?`, מספר ${cell.number}`:''}`} aria-invalid={checked&&!!answers[cell.key]&&normalize(answers[cell.key])!==cell.letter} autoComplete="off" spellCheck={false} value={answers[cell.key]||''} onFocus={()=>selectCell(cell.key)} onClick={()=>selectCell(cell.key)} onDoubleClick={()=>selectCell(cell.key,true)} onChange={e=>{const value=e.target.value.replace(/[^א-ת]/g,'').slice(-1);setAnswers(a=>({...a,[cell.key]:value}));setChecked(false);if(value)move(cell.key,1)}} onKeyDown={e=>{if(e.key==='Backspace'&&!answers[cell.key]){e.preventDefault();move(cell.key,-1)}if(e.key===' '){e.preventDefault();selectCell(cell.key,true)}if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key)){e.preventDefault();const [dr,dc]=({ArrowLeft:[0,1],ArrowRight:[0,-1],ArrowUp:[-1,0],ArrowDown:[1,0]})[e.key];refs.current[`${cell.r+dr},${cell.c+dc}`]?.focus()}}}/></div>)}</div></div>
      <p className="puzzle-hint no-print">מאוזן: מימין לשמאל. מאונך: מלמעלה למטה. לחצו על רמז כדי לבחור מילה; במחשב אפשר להתקדם עם החצים.</p>
    </div><aside className="crossword-clues">{Object.entries(DIRECTIONS).map(([dir,label])=><section key={dir}><h3>{label} <span>{dir==='across'?'←':'↓'}</span></h3><ol>{puzzle.placed.map((word,i)=>word.d===dir&&<li key={`${word.number}-${dir}`}><button onClick={()=>choose(i)} aria-pressed={selected===i}><b>{word.number}</b><span>{word.clue} <small>({word.word.length})</small></span></button></li>)}</ol></section>)}</aside></div>
    <Actions check={()=>setChecked(true)} reset={()=>{setAnswers({});setChecked(false)}} success={checked&&solved} message={checked?(solved?'🎉 כל הכבוד! פתרתם את התשבץ.':`${correct} מתוך ${total} אותיות נכונות. תאים שגויים מסומנים בקו אדום מקווקו.`):''}/></>
}

function SudokuGame({n,seed}){const game=useMemo(()=>sudoku(n,seed),[n,seed]),[values,setValues]=useState({}),[checked,setChecked]=useState(false),complete=game.solution.every((v,i)=>(game.board[i]||Number(values[i]))===v);return <><div className="puzzle-paper-title"><div><small>לוח {n} × {n} · פתרון יחיד</small><h2>סודוקו</h2></div></div><p>מלאו את הספרות 1–{n}, כך שכל ספרה תופיע פעם אחת בכל שורה, עמודה וריבוע.</p><div className="sudoku-board" style={{gridTemplateColumns:`repeat(${n},1fr)`}} dir="ltr">{game.board.map((given,i)=><div key={i} style={{borderRightWidth:(i%n+1)%Math.sqrt(n)===0?3:1,borderBottomWidth:(Math.floor(i/n)+1)%Math.sqrt(n)===0?3:1}} className={`${given?'sudoku-given':''} ${checked&&values[i]&&Number(values[i])!==game.solution[i]?'cell-wrong':''}`}>{given?<span>{given}</span>:<input aria-label={`שורה ${Math.floor(i/n)+1}, עמודה ${i%n+1}`} inputMode="numeric" autoComplete="off" value={values[i]||''} onChange={e=>{setValues(v=>({...v,[i]:e.target.value.replace(new RegExp(`[^1-${n}]`,'g'),'').slice(-1)}));setChecked(false)}}/>}</div>)}</div><Actions check={()=>setChecked(true)} reset={()=>{setValues({});setChecked(false)}} success={checked&&complete} message={checked?(complete?'🎉 הסודוקו פתור!':'השלימו את התאים הריקים ותקנו את התאים המסומנים.'):''}/></>}

function SearchGame({entries,seed,diagonal,custom}){const game=useMemo(()=>wordSearch(entries.map(x=>x[0]),seed,diagonal),[entries,seed,diagonal]),[start,setStart]=useState(null),[found,setFound]=useState([]),[message,setMessage]=useState(''),foundCells=new Set(game.placed.filter(p=>found.includes(p.word)).flatMap(p=>p.keys));function select(i){if(start===null){setStart(i);setMessage('עכשיו בחרו את האות האחרונה של המילה.');return}const word=game.placed.find(p=>(p.keys[0]===start&&p.keys.at(-1)===i)||(p.keys[0]===i&&p.keys.at(-1)===start));if(word){setFound(f=>f.includes(word.word)?f:[...f,word.word]);setMessage(`מצאתם: ${word.word}!`)}else setMessage('המילה אינה ברשימה. נסו לבחור שוב אות ראשונה ואחרונה.');setStart(null)}return <><div className="puzzle-paper-title"><div><small>{found.length} מתוך {game.placed.length} מילים נמצאו</small><h2>{custom?'התפזורת שלי':'תפזורת'}</h2></div></div><p>לחצו על האות הראשונה ואז על האחרונה של מילה. חפשו מימין לשמאל ומלמעלה למטה{diagonal?' וגם באלכסון':''}.</p><div className="search-workspace"><div className="puzzle-board-scroll"><div className="wordsearch-board" style={{gridTemplateColumns:`repeat(${game.n},1fr)`}}>{game.grid.map((letter,i)=><button key={i} aria-label={`${letter}, שורה ${Math.floor(i/game.n)+1}, עמודה ${i%game.n+1}`} aria-pressed={start===i||foundCells.has(i)} className={`${foundCells.has(i)?'found-letter':''} ${start===i?'start-letter':''}`} onClick={()=>select(i)}>{letter}</button>)}</div></div><ul className="wordsearch-list">{game.placed.map(p=><li key={p.word} className={found.includes(p.word)?'found-word':''}>{found.includes(p.word)?'✓ ':''}{p.word}</li>)}</ul></div><Actions check={()=>setMessage(found.length===game.placed.length?'🎉 מצאתם את כל המילים!':`מצאתם ${found.length} מתוך ${game.placed.length} מילים.`)} reset={()=>{setFound([]);setStart(null);setMessage('')}} success={found.length===game.placed.length} message={found.length===game.placed.length?'🎉 מצאתם את כל המילים!':message}/></>}

function FillGame({seed,custom}){const questions=useMemo(()=>{const list=custom?custom.map(([s,a])=>[s,a]):SENTENCES;return Array.from({length:Math.min(6,list.length)},(_,i)=>list[(i+seed-1)%list.length])},[seed,custom]),[answers,setAnswers]=useState({}),[checked,setChecked]=useState(false),solved=questions.every((q,i)=>normalize(answers[i]||'')===normalize(q[1]));return <><div className="puzzle-paper-title"><h2>משלימים את המשפט</h2></div><p>כתבו את המילה החסרה. אפשר להיעזר במחסן המילים.</p><div className="fill-word-bank">{[...questions].sort((a,b)=>a[1].localeCompare(b[1],'he')).map((q,i)=><span key={i}>{q[1]}</span>)}</div><ol className="fill-questions">{questions.map(([sentence,answer],i)=><li key={i}><label htmlFor={`fill-${i}`}>{sentence}</label><input id={`fill-${i}`} autoComplete="off" value={answers[i]||''} className={checked?(normalize(answers[i]||'')===normalize(answer)?'cell-correct':'cell-wrong'):''} onChange={e=>{setAnswers(a=>({...a,[i]:e.target.value}));setChecked(false)}}/></li>)}</ol><Actions check={()=>setChecked(true)} reset={()=>{setAnswers({});setChecked(false)}} success={checked&&solved} message={checked?(solved?'🎉 השלמתם את כל המשפטים!':'בדקו את המילים המסומנות ונסו שוב.'):''}/></>}

function NumberGame({seed}){const game=useMemo(()=>{const rng=random(seed),solution=Array.from({length:9},()=>1+Math.floor(rng()*9));return {solution,rows:[0,1,2].map(r=>solution.slice(r*3,r*3+3).reduce((a,b)=>a+b)),cols:[0,1,2].map(c=>solution[c]+solution[c+3]+solution[c+6])}},[seed]),[answers,setAnswers]=useState({}),[checked,setChecked]=useState(false),value=i=>i%4===0?game.solution[i]:Number(answers[i]||0),solved=[0,1,2].every(r=>[0,1,2].reduce((sum,c)=>sum+value(r*3+c),0)===game.rows[r])&&[0,1,2].every(c=>[0,1,2].reduce((sum,r)=>sum+value(r*3+c),0)===game.cols[c])&&Array.from({length:9},(_,i)=>value(i)).every(v=>v>=1&&v<=9);return <><div className="puzzle-paper-title"><h2>ריבועי חשבון</h2></div><p>מלאו ספרות 1–9 כך שסכום כל שורה וכל עמודה יתאים למספר שבשוליים. ספרות יכולות לחזור, וייתכן יותר מפתרון אחד.</p><div className="number-square" dir="ltr">{[0,1,2].map(r=><div className="number-row" key={r}>{[0,1,2].map(c=>{const i=r*3+c;return i%4===0?<span className="number-given" key={c}>{game.solution[i]}</span>:<input key={c} aria-label={`שורה ${r+1}, עמודה ${c+1}`} inputMode="numeric" value={answers[i]||''} onChange={e=>{setAnswers(a=>({...a,[i]:e.target.value.replace(/[^1-9]/g,'').slice(-1)}));setChecked(false)}}/>})}<b aria-label={`סכום שורה ${r+1}: ${game.rows[r]}`}>→ {game.rows[r]}</b></div>)}<div className="number-row">{game.cols.map((v,i)=><b key={i} aria-label={`סכום עמודה ${i+1}: ${v}`}>↓ {v}</b>)}</div></div><Actions check={()=>setChecked(true)} reset={()=>{setAnswers({});setChecked(false)}} success={checked&&solved} message={checked?(solved?'🎉 כל הסכומים מתאימים!':'עדיין יש סכום שאינו מתאים או תא ריק. חברו ובדקו שוב.'):''}/></>}
