// Generated practice data for the gifted-test pages (number series + shape matrices).
// Each series is checked against its rule in tests/gifted.test.mjs; each matrix answer is the rule-generated missing cell.

export const SERIES = [
  { id: 's01', level: 1, rule: {"k":"cycle","a":2,"ops":[["+",2]]}, seq: [2,4,6,8,10], options: [14,12,10,13], answer: 1 },
  { id: 's02', level: 1, rule: {"k":"cycle","a":5,"ops":[["+",5]]}, seq: [5,10,15,20,25], options: [32,28,30,31], answer: 2 },
  { id: 's03', level: 1, rule: {"k":"cycle","a":30,"ops":[["-",3]]}, seq: [30,27,24,21,18], options: [17,13,16,15], answer: 3 },
  { id: 's04', level: 1, rule: {"k":"cycle","a":3,"ops":[["+",4]]}, seq: [3,7,11,15,19], options: [23,25,21,24], answer: 0 },
  { id: 's05', level: 1, rule: {"k":"cycle","a":100,"ops":[["-",10]]}, seq: [100,90,80,70,60], options: [52,50,48,51], answer: 1 },
  { id: 's06', level: 1, rule: {"k":"cycle","a":7,"ops":[["+",7]]}, seq: [7,14,21,28,35], options: [44,40,42,43], answer: 2 },
  { id: 's07', level: 1, rule: {"k":"cycle","a":1,"ops":[["*",2]]}, seq: [1,2,4,8,16], options: [24,34,30,32], answer: 3 },
  { id: 's08', level: 1, rule: {"k":"cycle","a":1,"ops":[["+",2],["+",1]]}, seq: [1,3,4,6,7,9], options: [10,11,12,8], answer: 0 },
  { id: 's09', level: 1, rule: {"k":"cycle","a":50,"ops":[["-",5]]}, seq: [50,45,40,35,30], options: [27,25,23,26], answer: 1 },
  { id: 's10', level: 1, rule: {"k":"cycle","a":64,"ops":[["/",2]]}, seq: [64,32,16,8,4], options: [0,4,3,2], answer: 3 },
  { id: 's11', level: 2, rule: {"k":"cycle","a":2,"ops":[["*",3]]}, seq: [2,6,18,54], options: [162,90,164,160], answer: 0 },
  { id: 's12', level: 2, rule: {"k":"grow","a":1,"d":1,"dd":1}, seq: [1,2,4,7,11,16], options: [21,22,24,20], answer: 1 },
  { id: 's13', level: 2, rule: {"k":"fib","a":1,"b":1}, seq: [1,1,2,3,5,8], options: [11,15,13,14], answer: 2 },
  { id: 's14', level: 2, rule: {"k":"squares","from":1}, seq: [1,4,9,16,25], options: [34,38,37,36], answer: 3 },
  { id: 's15', level: 2, rule: {"k":"inter","x":{"a":1,"d":1},"y":{"a":10,"d":10}}, seq: [1,10,2,20,3,30], options: [4,57,6,2], answer: 0 },
  { id: 's16', level: 2, rule: {"k":"cycle","a":10,"ops":[["+",5],["-",2]]}, seq: [10,15,13,18,16,21], options: [26,19,21,17], answer: 1 },
  { id: 's17', level: 2, rule: {"k":"cycle","a":1,"ops":[["*",3]]}, seq: [1,3,9,27], options: [45,83,81,79], answer: 2 },
  { id: 's18', level: 2, rule: {"k":"cycle","a":81,"ops":[["/",3]]}, seq: [81,27,9,3], options: [3,2,0,1], answer: 3 },
  { id: 's19', level: 2, rule: {"k":"grow","a":3,"d":3,"dd":1}, seq: [3,6,10,15,21], options: [28,27,30,26], answer: 0 },
  { id: 's20', level: 2, rule: {"k":"inter","x":{"a":5,"d":5},"y":{"a":50,"d":-5}}, seq: [5,50,10,45,15,40], options: [65,22,20,18], answer: 2 },
  { id: 's21', level: 3, rule: {"k":"cycle","a":2,"ops":[["*",2],["+",1]]}, seq: [2,4,5,10,11,22], options: [33,25,21,23], answer: 3 },
  { id: 's22', level: 3, rule: {"k":"affine","a":1,"m":2,"c":1}, seq: [1,3,7,15,31], options: [63,47,65,61], answer: 0 },
  { id: 's23', level: 3, rule: {"k":"grow","a":2,"d":2,"dd":2}, seq: [2,4,8,14,22], options: [30,32,34,33], answer: 1 },
  { id: 's24', level: 3, rule: {"k":"inter","x":{"a":20,"d":-2},"y":{"a":1,"d":3}}, seq: [20,1,18,4,16,7], options: [16,12,14,15], answer: 2 },
  { id: 's25', level: 3, rule: {"k":"grow","a":50,"d":-1,"dd":-1}, seq: [50,49,47,44,40], options: [36,37,33,35], answer: 3 },
  { id: 's26', level: 3, rule: {"k":"fib","a":2,"b":3}, seq: [2,3,5,8,13], options: [21,18,23,19], answer: 0 },
  { id: 's27', level: 3, rule: {"k":"cycle","a":3,"ops":[["+",3],["*",2]]}, seq: [3,6,12,15,30,33], options: [36,66,68,64], answer: 1 },
  { id: 's28', level: 3, rule: {"k":"squares","from":2}, seq: [4,9,16,25,36], options: [47,51,49,50], answer: 2 },
  { id: 's29', level: 3, rule: {"k":"affine","a":2,"m":2,"c":-1}, seq: [2,3,5,9,17], options: [25,35,31,33], answer: 3 },
  { id: 's30', level: 3, rule: {"k":"cycle","a":1,"ops":[["+",1],["+",2],["+",3]]}, seq: [1,2,4,7,8,10,13], options: [16,14,12,15], answer: 1 },
]

export const MATRICES = [
  { id: 'm01', level: 1, vary: {"shape":{"by":"c","vals":["circle","square","triangle"]}}, fixed: {},
    options: [{"shape":"circle","count":1,"fill":"empty","size":"m","rot":0},{"shape":"triangle","count":1,"fill":"empty","size":"m","rot":0},{"shape":"square","count":1,"fill":"empty","size":"m","rot":0},{"shape":"triangle","count":1,"fill":"striped","size":"m","rot":0}], answer: 1 },
  { id: 'm02', level: 1, vary: {"count":{"by":"c","vals":[1,2,3]}}, fixed: {"shape":"star"},
    options: [{"shape":"star","count":3,"fill":"empty","size":"m","rot":0},{"shape":"star","count":1,"fill":"empty","size":"m","rot":0},{"shape":"star","count":2,"fill":"empty","size":"m","rot":0},{"shape":"star","count":3,"fill":"striped","size":"m","rot":0}], answer: 0 },
  { id: 'm03', level: 1, vary: {"fill":{"by":"r","vals":["empty","striped","full"]}}, fixed: {"shape":"square"},
    options: [{"shape":"square","count":1,"fill":"empty","size":"m","rot":0},{"shape":"square","count":1,"fill":"striped","size":"m","rot":0},{"shape":"square","count":1,"fill":"full","size":"s","rot":0},{"shape":"square","count":1,"fill":"full","size":"m","rot":0}], answer: 3 },
  { id: 'm04', level: 1, vary: {"size":{"by":"c","vals":["s","m","l"]}}, fixed: {"shape":"heart","fill":"full"},
    options: [{"shape":"heart","count":1,"fill":"full","size":"s","rot":0},{"shape":"heart","count":1,"fill":"full","size":"m","rot":0},{"shape":"heart","count":1,"fill":"full","size":"l","rot":0},{"shape":"heart","count":1,"fill":"empty","size":"l","rot":0}], answer: 2 },
  { id: 'm05', level: 1, vary: {"rot":{"by":"c","vals":[0,90,180]}}, fixed: {"shape":"arrow","fill":"full"},
    options: [{"shape":"arrow","count":1,"fill":"full","size":"m","rot":0},{"shape":"arrow","count":1,"fill":"full","size":"m","rot":180},{"shape":"arrow","count":1,"fill":"full","size":"m","rot":90},{"shape":"arrow","count":1,"fill":"empty","size":"m","rot":180}], answer: 1 },
  { id: 'm06', level: 1, vary: {"shape":{"by":"r","vals":["triangle","diamond","hexagon"]}}, fixed: {"fill":"full"},
    options: [{"shape":"hexagon","count":1,"fill":"full","size":"m","rot":0},{"shape":"triangle","count":1,"fill":"full","size":"m","rot":0},{"shape":"diamond","count":1,"fill":"full","size":"m","rot":0},{"shape":"hexagon","count":1,"fill":"empty","size":"m","rot":0}], answer: 0 },
  { id: 'm07', level: 1, vary: {"count":{"by":"r","vals":[1,2,3]}}, fixed: {"shape":"heart"},
    options: [{"shape":"heart","count":1,"fill":"empty","size":"m","rot":0},{"shape":"heart","count":2,"fill":"empty","size":"m","rot":0},{"shape":"heart","count":3,"fill":"striped","size":"m","rot":0},{"shape":"heart","count":3,"fill":"empty","size":"m","rot":0}], answer: 3 },
  { id: 'm08', level: 2, vary: {"shape":{"by":"l","vals":["circle","square","triangle"]}}, fixed: {"fill":"striped"},
    options: [{"shape":"circle","count":1,"fill":"striped","size":"m","rot":0},{"shape":"triangle","count":1,"fill":"striped","size":"m","rot":0},{"shape":"square","count":1,"fill":"striped","size":"m","rot":0},{"shape":"square","count":1,"fill":"empty","size":"m","rot":0}], answer: 2 },
  { id: 'm09', level: 2, vary: {"fill":{"by":"l","vals":["empty","striped","full"]}}, fixed: {"shape":"hexagon"},
    options: [{"shape":"hexagon","count":1,"fill":"empty","size":"m","rot":0},{"shape":"hexagon","count":1,"fill":"striped","size":"m","rot":0},{"shape":"hexagon","count":1,"fill":"full","size":"m","rot":0},{"shape":"hexagon","count":1,"fill":"striped","size":"s","rot":0}], answer: 1 },
  { id: 'm10', level: 2, vary: {"shape":{"by":"c","vals":["circle","star","diamond"]},"fill":{"by":"r","vals":["empty","striped","full"]}}, fixed: {},
    options: [{"shape":"circle","count":1,"fill":"full","size":"m","rot":0},{"shape":"diamond","count":1,"fill":"empty","size":"m","rot":0},{"shape":"star","count":1,"fill":"full","size":"m","rot":0},{"shape":"diamond","count":1,"fill":"full","size":"m","rot":0}], answer: 3 },
  { id: 'm11', level: 2, vary: {"count":{"by":"c","vals":[1,2,3]},"shape":{"by":"r","vals":["square","triangle","heart"]}}, fixed: {},
    options: [{"shape":"heart","count":1,"fill":"empty","size":"m","rot":0},{"shape":"square","count":3,"fill":"empty","size":"m","rot":0},{"shape":"heart","count":3,"fill":"empty","size":"m","rot":0},{"shape":"heart","count":2,"fill":"empty","size":"m","rot":0}], answer: 2 },
  { id: 'm12', level: 2, vary: {"rot":{"by":"c","vals":[0,90,180]},"fill":{"by":"r","vals":["empty","full","striped"]}}, fixed: {"shape":"arrow"},
    options: [{"shape":"arrow","count":1,"fill":"striped","size":"m","rot":0},{"shape":"arrow","count":1,"fill":"striped","size":"m","rot":180},{"shape":"arrow","count":1,"fill":"empty","size":"m","rot":180},{"shape":"arrow","count":1,"fill":"striped","size":"m","rot":90}], answer: 1 },
  { id: 'm13', level: 2, vary: {"size":{"by":"r","vals":["s","m","l"]},"shape":{"by":"c","vals":["hexagon","circle","star"]}}, fixed: {"fill":"full"},
    options: [{"shape":"star","count":1,"fill":"full","size":"l","rot":0},{"shape":"star","count":1,"fill":"full","size":"s","rot":0},{"shape":"hexagon","count":1,"fill":"full","size":"l","rot":0},{"shape":"circle","count":1,"fill":"full","size":"l","rot":0}], answer: 0 },
  { id: 'm14', level: 2, vary: {"count":{"by":"c","vals":[3,2,1]},"fill":{"by":"r","vals":["full","striped","empty"]}}, fixed: {"shape":"triangle"},
    options: [{"shape":"triangle","count":3,"fill":"empty","size":"m","rot":0},{"shape":"triangle","count":1,"fill":"full","size":"m","rot":0},{"shape":"triangle","count":2,"fill":"empty","size":"m","rot":0},{"shape":"triangle","count":1,"fill":"empty","size":"m","rot":0}], answer: 3 },
  { id: 'm15', level: 2, vary: {"count":{"by":"s","vals":[1,2,3,4,5]}}, fixed: {"shape":"diamond","fill":"full","size":"s"},
    options: [{"shape":"diamond","count":1,"fill":"full","size":"s","rot":0},{"shape":"diamond","count":4,"fill":"full","size":"s","rot":0},{"shape":"diamond","count":5,"fill":"full","size":"s","rot":0},{"shape":"diamond","count":2,"fill":"full","size":"s","rot":0}], answer: 2 },
  { id: 'm16', level: 3, vary: {"rot":{"by":"l","vals":[0,90,180]},"fill":{"by":"c","vals":["empty","striped","full"]}}, fixed: {"shape":"arrow"},
    options: [{"shape":"arrow","count":1,"fill":"full","size":"m","rot":0},{"shape":"arrow","count":1,"fill":"full","size":"m","rot":90},{"shape":"arrow","count":1,"fill":"empty","size":"m","rot":90},{"shape":"arrow","count":1,"fill":"striped","size":"m","rot":0}], answer: 1 },
  { id: 'm17', level: 3, vary: {"shape":{"by":"l","vals":["star","circle","square"]},"count":{"by":"r","vals":[1,2,3]}}, fixed: {"fill":"full","size":"s"},
    options: [{"shape":"circle","count":3,"fill":"full","size":"s","rot":0},{"shape":"star","count":3,"fill":"full","size":"s","rot":0},{"shape":"circle","count":1,"fill":"full","size":"s","rot":0},{"shape":"star","count":2,"fill":"full","size":"s","rot":0}], answer: 0 },
  { id: 'm18', level: 3, vary: {"shape":{"by":"l","vals":["star","heart","circle"]},"fill":{"by":"k","vals":["empty","striped","full"]}}, fixed: {},
    options: [{"shape":"star","count":1,"fill":"empty","size":"m","rot":0},{"shape":"heart","count":1,"fill":"striped","size":"m","rot":0},{"shape":"star","count":1,"fill":"full","size":"m","rot":0},{"shape":"heart","count":1,"fill":"empty","size":"m","rot":0}], answer: 3 },
  { id: 'm19', level: 2, vary: {"count":{"by":"c","vals":[2,3,4]},"size":{"by":"r","vals":["l","m","s"]}}, fixed: {"shape":"circle","fill":"striped"},
    options: [{"shape":"circle","count":2,"fill":"striped","size":"s","rot":0},{"shape":"circle","count":4,"fill":"striped","size":"l","rot":0},{"shape":"circle","count":4,"fill":"striped","size":"s","rot":0},{"shape":"circle","count":3,"fill":"striped","size":"s","rot":0}], answer: 2 },
  { id: 'm20', level: 2, vary: {"rot":{"by":"r","vals":[0,90,180]},"count":{"by":"c","vals":[1,2,3]}}, fixed: {"shape":"arrow","fill":"full","size":"s"},
    options: [{"shape":"arrow","count":3,"fill":"full","size":"s","rot":180},{"shape":"arrow","count":3,"fill":"full","size":"s","rot":0},{"shape":"arrow","count":1,"fill":"full","size":"s","rot":180},{"shape":"arrow","count":2,"fill":"full","size":"s","rot":180}], answer: 0 },
  { id: 'm21', level: 3, vary: {"shape":{"by":"c","vals":["square","circle","triangle"]},"count":{"by":"r","vals":[1,2,3]},"fill":{"by":"l","vals":["empty","striped","full"]}}, fixed: {"size":"s"},
    options: [{"shape":"square","count":3,"fill":"striped","size":"s","rot":0},{"shape":"triangle","count":1,"fill":"striped","size":"s","rot":0},{"shape":"triangle","count":3,"fill":"empty","size":"s","rot":0},{"shape":"triangle","count":3,"fill":"striped","size":"s","rot":0}], answer: 3 },
  { id: 'm22', level: 3, vary: {"rot":{"by":"c","vals":[0,90,180]},"size":{"by":"r","vals":["s","m","l"]},"fill":{"by":"l","vals":["empty","striped","full"]}}, fixed: {"shape":"arrow"},
    options: [{"shape":"arrow","count":1,"fill":"striped","size":"l","rot":0},{"shape":"arrow","count":1,"fill":"striped","size":"s","rot":180},{"shape":"arrow","count":1,"fill":"striped","size":"l","rot":180},{"shape":"arrow","count":1,"fill":"empty","size":"l","rot":180}], answer: 2 },
  { id: 'm23', level: 3, vary: {"count":{"by":"s","vals":[1,2,3,4,5]},"fill":{"by":"r","vals":["empty","striped","full"]}}, fixed: {"shape":"circle","size":"s"},
    options: [{"shape":"circle","count":1,"fill":"full","size":"s","rot":0},{"shape":"circle","count":5,"fill":"full","size":"s","rot":0},{"shape":"circle","count":5,"fill":"empty","size":"s","rot":0},{"shape":"circle","count":4,"fill":"full","size":"s","rot":0}], answer: 1 },
  { id: 'm24', level: 3, vary: {"shape":{"by":"k","vals":["square","diamond","triangle"]},"count":{"by":"l","vals":[1,2,3]}}, fixed: {"fill":"full","size":"s"},
    options: [{"shape":"square","count":2,"fill":"full","size":"s","rot":0},{"shape":"diamond","count":2,"fill":"full","size":"s","rot":0},{"shape":"square","count":1,"fill":"full","size":"s","rot":0},{"shape":"triangle","count":1,"fill":"full","size":"s","rot":0}], answer: 0 },
  { id: 'm25', level: 3, vary: {"rot":{"by":"c","vals":[90,180,270]},"fill":{"by":"l","vals":["empty","striped","full"]}}, fixed: {"shape":"arrow"},
    options: [{"shape":"arrow","count":1,"fill":"striped","size":"m","rot":90},{"shape":"arrow","count":1,"fill":"empty","size":"m","rot":270},{"shape":"arrow","count":1,"fill":"empty","size":"m","rot":180},{"shape":"arrow","count":1,"fill":"striped","size":"m","rot":270}], answer: 3 },
  { id: 'm26', level: 2, vary: {"shape":{"by":"r","vals":["circle","hexagon","square"]},"size":{"by":"c","vals":["s","m","l"]}}, fixed: {"fill":"full"},
    options: [{"shape":"circle","count":1,"fill":"full","size":"l","rot":0},{"shape":"square","count":1,"fill":"full","size":"s","rot":0},{"shape":"square","count":1,"fill":"full","size":"l","rot":0},{"shape":"square","count":1,"fill":"full","size":"m","rot":0}], answer: 2 },
  { id: 'm27', level: 3, vary: {"count":{"by":"r","vals":[1,2,3]},"rot":{"by":"l","vals":[0,90,180]}}, fixed: {"shape":"arrow","fill":"full","size":"s"},
    options: [{"shape":"arrow","count":1,"fill":"full","size":"s","rot":90},{"shape":"arrow","count":3,"fill":"full","size":"s","rot":90},{"shape":"arrow","count":3,"fill":"full","size":"s","rot":0},{"shape":"arrow","count":2,"fill":"full","size":"s","rot":0}], answer: 1 },
  { id: 'm28', level: 3, vary: {"shape":{"by":"l","vals":["heart","diamond","star"]},"size":{"by":"k","vals":["s","m","l"]},"count":{"by":"c","vals":[1,2,3]}}, fixed: {"fill":"full"},
    options: [{"shape":"diamond","count":3,"fill":"full","size":"s","rot":0},{"shape":"heart","count":3,"fill":"full","size":"s","rot":0},{"shape":"diamond","count":3,"fill":"full","size":"m","rot":0},{"shape":"diamond","count":1,"fill":"full","size":"s","rot":0}], answer: 0 },
  { id: 'm29', level: 3, vary: {"count":{"by":"s","vals":[1,2,3,4,5]},"fill":{"by":"l","vals":["empty","striped","full"]}}, fixed: {"shape":"heart","size":"s"},
    options: [{"shape":"heart","count":1,"fill":"striped","size":"s","rot":0},{"shape":"heart","count":5,"fill":"empty","size":"s","rot":0},{"shape":"heart","count":4,"fill":"empty","size":"s","rot":0},{"shape":"heart","count":5,"fill":"striped","size":"s","rot":0}], answer: 3 },
  { id: 'm30', level: 3, vary: {"shape":{"by":"c","vals":["star","circle","triangle"]},"fill":{"by":"r","vals":["empty","striped","full"]},"size":{"by":"l","vals":["s","m","l"]}}, fixed: {},
    options: [{"shape":"star","count":1,"fill":"full","size":"m","rot":0},{"shape":"triangle","count":1,"fill":"full","size":"m","rot":0},{"shape":"triangle","count":1,"fill":"empty","size":"m","rot":0},{"shape":"triangle","count":1,"fill":"full","size":"s","rot":0}], answer: 1 },
]
