import { useMemo, useState } from 'react'
import SEO from '../components/ui/SEO'
import Breadcrumbs from '../components/ui/Breadcrumbs'

const EVENTS=[['birthday','🎂 מסיבת יום הולדת'],['kids','🧸 אירוע בגן'],['family','🏠 אירוע משפחתי'],['bar','🧸 בר/בת מצווה'],['adults','🏙️ אירוע למבוגרים']]
const BUDGETS=[['low','💚 חסכוני'],['medium','💛 רגיל'],['high','💜 מפנק']]
const money=n=>`${Math.round(n).toLocaleString('he-IL')} ₪`
function calculate({guests,age,duration,meal,budget,event}){
 const foodFactor=meal==='pizza'?1:meal==='snacks'?.55:meal==='light'?.75:.3, pizzaRate=age==='3-5'?.20:age==='6-9'?.30:age==='10-13'?.34:.38
 const pizzas=Math.max(1,Math.ceil(guests*pizzaRate*foodFactor)),drinks=Math.max(2,Math.ceil(guests*(duration==='2-3'?.62:duration==='1-2'?.45:.35))),snacks=meal==='none'?0:Math.ceil(guests*(meal==='snacks'?.8:.4)),cake=(event==='birthday'||event==='bar')?Math.max(1,Math.ceil(guests/24)):0,cups=Math.ceil(guests*1.5),plates=meal==='none'?0:Math.ceil(guests*1.2),favors=(event==='birthday'||event==='kids')?guests:0
 const p={low:{pizza:45,drink:9,snack:3,cake:80,cup:.55,plate:.55,favor:8},medium:{pizza:55,drink:12,snack:5,cake:120,cup:1,plate:1,favor:15},high:{pizza:68,drink:16,snack:8,cake:180,cup:1.6,plate:1.6,favor:25}}[budget]
 const rows=[['🍕','אוכל',pizzas?`${pizzas} פיצות משפחתיות`:'אין ארוחה מלאה',pizzas*p.pizza],['🥤','שתייה',`${drinks} בקבוקים של 1.5 ליטר`,drinks*p.drink],['🍿','נשנושים',snacks?`${snacks} שקיות חטיפים`:'לא נדרש',snacks*p.snack],['🎂','עוגה',cake?`${cake} ${cake>1?'עוגות':'עוגה'} למסיבה`:'לא נדרש',cake*p.cake],['🍽️','חד־פעמי',`${cups} כוסות${plates?` · ${plates} צלחות`:''}`,cups*p.cup+plates*p.plate],['🎁','שקיות הפתעה',favors?`${favors} שקיות`:'לא נדרש',favors*p.favor]].filter(x=>x[3]||x[1]==='שתייה'||x[1]==='חד־פעמי')
 return {rows,total:rows.reduce((sum,row)=>sum+row[3],0)}
}
export default function Calculator(){
 const [event,setEvent]=useState('birthday'),[guests,setGuests]=useState(15),[age,setAge]=useState('6-9'),[duration,setDuration]=useState('2-3'),[meal,setMeal]=useState('pizza'),[budget,setBudget]=useState('medium'),[shown,setShown]=useState(false)
 const result=useMemo(()=>calculate({event,guests,age,duration,meal,budget}),[event,guests,age,duration,meal,budget])
 const pick=(title,items,value,setter)=><section><h2 className="mb-3 text-2xl">{title}</h2><div className="flex flex-wrap gap-2">{items.map(([id,label])=><button key={id} onClick={()=>{setter(id);setShown(false)}} className={`rounded-2xl border px-4 py-2 font-bold ${value===id?'border-red-400 bg-red-500 text-white':'border-slate-300 bg-white'}`}>{label}</button>)}</div></section>
 return <div className="mx-auto max-w-5xl px-4 py-8"><SEO title="מחשבון מסיבה — כמה פיצות, שתייה ועוגה לקנות" description="מחשבון מסיבה חינמי: בוחרים סוג אירוע, מספר אורחים, גיל, משך ותקציב — ומקבלים רשימת קניות עם כמויות פיצה, שתייה וחטיפים ועלות משוערת בשקלים." path="/calculator"/><Breadcrumbs items={[{label:'ראשי',href:'/'},{label:'כלים'},{label:'מחשבון מסיבה'}]}/><header className="mb-7 text-center"><h1 className="text-4xl sm:text-5xl">🧮 מחשבון מסיבה</h1><p className="mt-2 text-lg text-[var(--muted-foreground)]">בוחרים פרטי אירוע — ומקבלים רשימת קניות ועלות משוערת.</p></header><section className="rounded-[28px] border border-[var(--border)] bg-white p-5 shadow-[0_8px_25px_rgb(25_36_75_/_8%)] sm:p-8"><div className="grid gap-7">{pick('⛺ סוג אירוע',EVENTS,event,setEvent)}<section><div className="flex items-end justify-between gap-4"><div><h2 className="text-2xl">🧑‍🤝‍🧑 מספר אורחים</h2><p className="text-[var(--muted-foreground)]">בין 5 ל־60 משתתפים</p></div><output className="rounded-2xl border-2 border-[var(--border)] bg-yellow-100 px-5 py-2 text-2xl font-bold">{guests}</output></div><input aria-label="מספר אורחים" type="range" min="5" max="60" value={guests} onChange={e=>{setGuests(+e.target.value);setShown(false)}} className="mt-4 w-full accent-red-500"/></section><div className="grid gap-7 sm:grid-cols-2">{pick('📍 גיל',[['3-5','3–5'],['6-9','6–9'],['10-13','10–13'],['adult','מבוגרים']],age,setAge)}{pick('⌛ משך האירוע',[['1-2','שעה–שעתיים'],['2-3','2–3 שעות'],['3+','3 שעות+']],duration,setDuration)}</div>{pick('🍕 ארוחה עיקרית',[['pizza','🍕 פיצה מוזמנת'],['light','🥪 ארוחה קלה'],['snacks','🍿 נשנושים'],['none','ללא אוכל']],meal,setMeal)}{pick('💰 רמת תקציב',BUDGETS,budget,setBudget)}<button onClick={()=>setShown(true)} className="rounded-2xl bg-red-500 px-6 py-4 text-2xl font-bold text-white shadow-[0_5px_0_#c73147]">🎉 חשבו לי!</button></div></section>{shown&&<section className="mt-8"><div className="mb-4 flex flex-wrap items-center justify-between gap-3"><h2 className="text-3xl">רשימת הקניות שלכם</h2><strong className="rounded-full bg-yellow-100 px-5 py-2 text-xl">סה״כ משוער: {money(result.total)}</strong></div><div className="grid gap-4">{result.rows.map(([emoji,title,amount,cost])=><article key={title} className="flex items-start justify-between gap-5 rounded-3xl border border-[var(--border)] bg-white p-5 shadow-[0_5px_16px_rgb(25_36_75_/_6%)]"><div><h3 className="text-2xl">{emoji} {title}</h3><p className="mt-2 text-lg">{amount}</p></div><strong className="whitespace-nowrap text-xl">{money(cost)}</strong></article>)}</div><p className="mt-4 text-sm text-[var(--muted-foreground)]">המחירים הם הערכה בלבד; אפשר לעדכן את התקציב ולחשב שוב.</p></section>}</div>
}
