import { useMemo, useState } from 'react'
import SEO from '../components/ui/SEO'
import Breadcrumbs from '../components/ui/Breadcrumbs'

const MODULES=[['letters','✏️','אותיות וכתיבה'],['reading','📖','קריאה ראשונה'],['math','🔢','משחקי חשבון'],['clock','🕐','מעבדת שעונים'],['months','📅','חודשים ועונות']]
const MONTHS=[['תשרי','🍎','סתיו',30],['חשוון','🍂','סתיו',30],['כסלו','🕎','חורף',29],['טבת','🧣','חורף',29],['שבט','🌳','חורף',30],['אדר','🎭','חורף',29],['ניסן','🌸','אביב',30],['אייר','🌼','אביב',29],['סיוון','📚','אביב',30],['תמוז','☀️','קיץ',29],['אב','🍉','קיץ',30],['אלול','🎒','קיץ',29]]
const WORDS=[['חתול','🐱'],['כלב','🐶'],['בית','🏠'],['שמש','☀️'],['ספר','📚'],['פרח','🌸']]
const fmt=n=>String(n).padStart(2,'0')

export default function ClassOnePrep(){
  const [module,setModule]=useState('letters'),[size,setSize]=useState('large'),[trace,setTrace]=useState(''),[clock,setClock]=useState(3),[answer,setAnswer]=useState(null),[mathLevel,setMathLevel]=useState('easy'),[score,setScore]=useState(0),[round,setRound]=useState(0),[month,setMonth]=useState(null)
  const active=MODULES.find(x=>x[0]===module)
  const equation=useMemo(()=>{const max=mathLevel==='easy'?10:mathLevel==='medium'?15:20;const a=(round*3)%Math.max(2,max-1)+1;const b=(round*5)%Math.max(2,max-a)+1;const subtract=round%2===1;return {a,b,subtract,correct:subtract?a-b:a+b}},[round,mathLevel])
  const options=useMemo(()=>[equation.correct,equation.correct+1,equation.correct+2,Math.max(0,equation.correct-1)].sort(()=>((round+1)*17)%7-3),[equation,round])
  return <div className="mx-auto max-w-6xl px-4 py-6 sm:py-8" dir="rtl"><SEO title="הכנה לכיתה א׳ | עוגה בוגה" description="מרכז משחקי להכנה לכיתה א׳: כתיבה בקווים, קריאה, חשבון, שעון וחודשים." path="/classroom/first-grade"/><Breadcrumbs items={[{label:'ראשי',href:'/'},{label:'כיתה',href:'/classroom'},{label:'הכנה לכיתה א׳'}]}/><header className="rounded-[32px] border-2 border-slate-200 bg-gradient-to-l from-violet-50 via-white to-pink-50 p-6 text-center shadow-[0_6px_0_#e5e7eb] sm:p-10"><div className="mb-2 text-5xl">🎒</div><h1 className="text-4xl font-black text-slate-900 sm:text-6xl">שלום, כיתה א׳!</h1><p className="mx-auto mt-3 max-w-2xl text-lg text-slate-600">תרגול צבעוני לילדים, להורים ולמורים — בוחרים לשונית ומתחילים.</p></header><nav aria-label="מודולי תרגול" className="my-7 grid grid-cols-2 gap-3 sm:grid-cols-5">{MODULES.map(([id,emoji,title])=><button key={id} onClick={()=>{setModule(id);setAnswer(null);setMonth(null)}} aria-pressed={module===id} className={`rounded-3xl border-2 p-4 text-right transition hover:-translate-y-1 ${module===id?'border-violet-500 bg-violet-50 shadow-[0_4px_0_#8b5cf6]':'border-slate-200 bg-white'}`}><span className="text-3xl">{emoji}</span><b className="mt-2 block text-base sm:text-lg">{title}</b><small className="mt-1 block text-slate-500">פעילות אינטראקטיבית</small></button>)}</nav><main className="mx-auto max-w-5xl rounded-[32px] border-2 border-slate-200 bg-white p-5 shadow-[0_7px_0_#dce1ee] sm:p-8"><div className="mb-6 flex flex-wrap items-center justify-between gap-3"><div><p className="text-sm font-bold text-violet-600">מודול נבחר</p><h2 className="text-3xl font-black">{active[1]} {active[2]}</h2></div><button onClick={()=>window.print()} className="no-print rounded-2xl bg-slate-900 px-5 py-3 font-bold text-white">🖨️ הדפסת דף</button></div>{module==='letters'&&<Letters size={size} setSize={setSize} trace={trace} setTrace={setTrace}/>} {module==='clock'&&<Clock hour={clock} setHour={setClock}/>} {module==='math'&&<MathGame equation={equation} options={options} answer={answer} setAnswer={setAnswer} level={mathLevel} setLevel={setMathLevel} score={score} setScore={setScore} next={()=>{setRound(r=>r+1);setAnswer(null)}}/>} {module==='reading'&&<Reading/>} {module==='months'&&<Months month={month} setMonth={setMonth}/>}</main></div>
}

function Letters({size,setSize,trace,setTrace}){const value=trace||'א';return <section className="rounded-3xl bg-pink-50 p-5 text-center"><div className="flex flex-wrap items-center justify-center gap-3"><label className="font-bold">כתבו אות או מילה<input value={trace} onChange={e=>setTrace(e.target.value.slice(0,12))} placeholder="למשל: אבא" className="mr-2 rounded-xl border-2 p-3"/></label><label className="font-bold">גודל<select value={size} onChange={e=>setSize(e.target.value)} className="mr-2 rounded-xl border-2 p-3"><option value="small">קטן</option><option value="medium">בינוני</option><option value="large">גדול</option></select></label></div><p className="mt-5 text-slate-600">עברו עם עיפרון על האותיות המקווקוות:</p><div className={`mx-auto my-5 max-w-3xl select-none border-2 border-dashed border-pink-300 bg-white p-8 font-black tracking-[.25em] text-pink-300 ${size==='small'?'text-5xl':size==='medium'?'text-7xl':'text-8xl'}`}>{value}</div><div className="flex justify-center gap-2 text-3xl" aria-label="בחירת צבע">{['#ef4444','#f59e0b','#22c55e','#3b82f6','#a855f7'].map(color=><button key={color} style={{color}} aria-label={`צבע ${color}`}>●</button>)}</div></section>}
function Clock({hour,setHour}){return <section className="rounded-3xl bg-emerald-50 p-5 text-center"><p className="mb-4 text-lg">לחצו על שעה ובחנו את המחוגים</p><div className="mx-auto flex size-64 items-center justify-center rounded-full border-8 border-emerald-400 bg-white text-3xl font-bold shadow-inner">🕐<span className="absolute mt-36 text-2xl">{fmt(hour)}:00</span></div><div className="mt-6 grid grid-cols-4 gap-2 sm:grid-cols-6">{[1,2,3,4,5,6,7,8,9,10,11,12].map(h=><button key={h} onClick={()=>setHour(h)} className={`rounded-xl border-2 p-3 font-bold ${hour===h?'border-violet-500 bg-violet-100':'bg-white'}`}>{h}:00</button>)}</div></section>}
function MathGame({equation,options,answer,setAnswer,level,setLevel,score,setScore,next}){function choose(v){setAnswer(v);if(v===equation.correct)setScore(s=>s+1)}return <section className="rounded-3xl bg-amber-50 p-5 text-center"><div className="mb-4 flex flex-wrap justify-center gap-2">{[['easy','קל עד 10'],['medium','בינוני עד 15'],['hard','קשה עד 20']].map(([id,label])=><button key={id} onClick={()=>{setLevel(id);setAnswer(null)}} className={`rounded-xl border-2 px-4 py-2 font-bold ${level===id?'border-pink-500 bg-pink-100':'bg-white'}`}>{label}</button>)}</div><p className="text-sm text-slate-600">ניקוד: {score}</p><div className="my-7 text-5xl font-black">{equation.a} {equation.subtract?'−':'+'} {equation.b} = ?</div><div className="grid grid-cols-2 gap-3 sm:grid-cols-4">{options.map(v=><button key={v} onClick={()=>choose(v)} className={`rounded-2xl border-2 p-4 text-2xl font-black ${answer!==null?(v===equation.correct?'border-green-500 bg-green-100':'border-slate-200 bg-white'):'border-slate-200 bg-white hover:bg-violet-50'}`}>{v}</button>)}</div>{answer!==null&&<div className="mt-5 text-xl font-bold">{answer===equation.correct?'✅ תשובה נכונה!':'❌ נסו שוב'}</div>}<button onClick={next} className="mt-5 rounded-xl bg-violet-600 px-5 py-3 font-bold text-white">תרגיל חדש ↻</button></section>}
function Reading(){const [target,setTarget]=useState(WORDS[0][0]),[chosen,setChosen]=useState(null);const item=WORDS.find(x=>x[0]===target);return <section className="rounded-3xl bg-blue-50 p-5 text-center"><p className="text-lg">מצאו את המילה שההורה בחר:</p><div className="my-3 text-3xl font-black">{item[1]} {target}</div><div className="grid grid-cols-2 gap-3 sm:grid-cols-3">{WORDS.map(([word,emoji])=><button key={word} onClick={()=>setChosen(word)} className={`rounded-2xl border-2 bg-white p-5 text-xl font-bold ${chosen===word?(word===target?'border-green-500 bg-green-100':'border-red-400 bg-red-50'):''}`}>{emoji}<br/>{word}</button>)}</div>{chosen&&<p className="mt-4 text-xl font-bold">{chosen===target?'✅ מצוין!':'❌ נסו שוב'}</p>}<button onClick={()=>{setTarget(WORDS[(WORDS.findIndex(x=>x[0]===target)+1)%WORDS.length][0]);setChosen(null)}} className="mt-5 rounded-xl bg-violet-600 px-5 py-3 font-bold text-white">מילה חדשה ↻</button></section>}
function Months({month,setMonth}){const selected=MONTHS.find(x=>x[0]===month);function speak(name){if('speechSynthesis' in window){window.speechSynthesis.cancel();window.speechSynthesis.speak(new SpeechSynthesisUtterance(name))}}return <section className="rounded-3xl bg-violet-50 p-4 sm:p-6"><div className="mb-5 flex flex-wrap items-center justify-between gap-2"><div><p className="text-sm font-bold text-violet-700">לוח השנה שלי</p><h3 className="text-2xl font-black">בחרו חודש ולמדו עליו</h3></div><span className="rounded-full bg-white px-4 py-2 font-bold text-violet-700">12 חודשים · 4 עונות</span></div><div className="grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-4">{MONTHS.map(([name,emoji,season,days])=><article key={name} className={`rounded-2xl border-2 bg-white p-4 text-center shadow-[0_3px_0_#e4ddf7] transition hover:-translate-y-1 ${month===name?'border-pink-500 bg-pink-50 shadow-[0_3px_0_#ec4899]':'border-slate-200'}`}><button onClick={()=>setMonth(name)} className="w-full font-bold"><span className="text-4xl">{emoji}</span><strong className="mt-2 block text-2xl">{name}</strong><span className="mt-1 inline-block rounded-full bg-slate-100 px-3 py-1 text-sm">{season} · {days} ימים</span></button><button onClick={()=>speak(name)} className="mt-3 rounded-xl border border-slate-200 px-3 py-1 text-sm font-bold" aria-label={`השמיעו את ${name}`}>🔊 השמיעו</button></article>)}</div>{selected&&<div className="mt-6 rounded-2xl border-2 border-pink-200 bg-white p-4 text-center" aria-live="polite"><p className="text-xl font-black">📅 בחרתם בחודש {selected[0]}</p><p className="mt-1 text-slate-600">הוא בחודשי {selected[2]} ויש בו בדרך כלל {selected[3]} ימים.</p><button onClick={()=>speak(`חודש ${selected[0]}, עונת ${selected[2]}`)} className="mt-3 rounded-xl bg-violet-600 px-5 py-2 font-bold text-white">🔊 הקשיבו לחודש</button></div>}</section>}
