import { useLayoutEffect, useMemo, useRef, useState } from 'react'
import SEO from '../components/ui/SEO'
import SeoBody, { faqSchema } from '../components/ui/SeoBody'
import Breadcrumbs from '../components/ui/Breadcrumbs'

const firstGradeFaq = [
  { q: 'כמה זמן לפני תחילת כיתה א׳ כדאי להתחיל להכין את הילד?', a: 'חודש-חודשיים לפני מספיקים בהחלט, בתנאי שההכנה נשארת קלה ומשחקית ולא הופכת ללחץ נוסף.' },
  { q: 'מה חשוב יותר, מיומנויות כתיבה או ביטחון עצמי?', a: 'שילוב של שניהם עובד הכי טוב, אבל ילד בטוח בעצמו שמגיע עם פחות מיומנות מסתגל בדרך כלל מהר יותר מילד מיומן אבל לחוץ.' },
]
const firstGradeBody = [
  'המעבר לכיתה א׳ מלחיץ הרבה הורים יותר מהילדים עצמם. הדרך היעילה ביותר להכין ילד היא דרך משחק, לא דרך תרגול פורמלי — פעילות עם מטרה ברורה עובדת הרבה יותר טוב מדף עבודה סתמי.',
  'חשוב לזכור שילד שמגיע לכיתה א׳ עם ביטחון עצמי גבוה לרוב מסתגל מהר יותר מילד שמגיע מלא ידע אבל לחוץ. שילוב של משחק כיפי לצד תרגול ממוקד עדיף על תרגול בלבד.',
  'טיפ להורים בקיץ שלפני כיתה א׳: הקדישו 10-15 דקות ביום, לא יותר, לפעילות ממוקדת, ותנו לשאר היום להיות משחק חופשי לגמרי.',
]
const firstGradeRelated = [ { label: 'מתחם לכיתה', href: '/classroom' }, { label: 'משחקים לכיתה א׳', href: '/games/kita-a' }, { label: 'משחקים ל-5 דקות פנויות', href: '/games/5-minutes' } ]

const MODULES=[['letters','✏️','אותיות וכתיבה'],['reading','📖','קריאה ראשונה'],['english','🔤','אנגלית ראשונה'],['math','🔢','משחקי חשבון'],['clock','🕐','מעבדת שעונים'],['months','📅','חודשים ועונות']]
const MONTHS=[['תשרי','🍎','סתיו',30],['חשוון','🍂','סתיו',30],['כסלו','🕎','חורף',29],['טבת','🧣','חורף',29],['שבט','🌳','חורף',30],['אדר','🎭','חורף',29],['ניסן','🌸','אביב',30],['אייר','🌼','אביב',29],['סיוון','📚','אביב',30],['תמוז','☀️','קיץ',29],['אב','🍉','קיץ',30],['אלול','🎒','קיץ',29]]
const WORDS=[['חתול','🐱'],['כלב','🐶'],['בית','🏠'],['שמש','☀️'],['ספר','📚'],['פרח','🌸']]
const ENGLISH_WORDS=[['CAT','חתול','🐱'],['DOG','כלב','🐶'],['HOUSE','בית','🏠'],['SUN','שמש','☀️'],['BOOK','ספר','📚'],['BALL','כדור','⚽'],['APPLE','תפוח','🍎'],['STAR','כוכב','⭐']]
const MATH_EMOJIS=['⚽','🧸','🚗','⭐','🍎','🐶','🦄','🎈']
const fmt=n=>String(n).padStart(2,'0')

export default function ClassOnePrep(){
  const [module,setModule]=useState('letters'),[size,setSize]=useState('large'),[trace,setTrace]=useState('אבא'),[clock,setClock]=useState(3),[answer,setAnswer]=useState(null),[mathLevel,setMathLevel]=useState('easy'),[score,setScore]=useState(0),[round,setRound]=useState(0),[month,setMonth]=useState(null)
  const activityRef=useRef(null)
  const [selectionCount,setSelectionCount]=useState(0)
  useLayoutEffect(()=>{
    if (!selectionCount) return
    activityRef.current?.focus({preventScroll:true})
    activityRef.current?.scrollIntoView({behavior:'instant',block:'start'})
  },[selectionCount])
  const active=MODULES.find(x=>x[0]===module)
  const equation=useMemo(()=>{const max=mathLevel==='easy'?10:mathLevel==='medium'?15:20;const a=(round*3)%Math.max(2,max-1)+1;const b=(round*5)%Math.max(2,max-a)+1;return {a,b,correct:a+b}},[round,mathLevel])
  const options=useMemo(()=>[equation.correct,equation.correct+1,equation.correct+2,Math.max(0,equation.correct-1)].sort(()=>((round+1)*17)%7-3),[equation,round])
  const selectModule=(id)=>{setModule(id);setAnswer(null);setMonth(null);setSelectionCount(count=>count+1)}
  return <div className="mx-auto max-w-6xl px-4 py-6 sm:py-8" dir="rtl"><SEO title="הכנה לכיתה א׳ — משחקים לקראת בית ספר" description="מרכז משחקי להכנה לכיתה א׳: כתיבה בקווים, קריאה בעברית ובאנגלית, חשבון, שעון וחודשים." path="/classroom/first-grade" structuredData={faqSchema(firstGradeFaq)}/><Breadcrumbs items={[{label:'ראשי',href:'/'},{label:'לכיתה',href:'/classroom'},{label:'הכנה לכיתה א׳'}]}/><header className="no-print rounded-[32px] border-2 border-slate-200 bg-gradient-to-l from-violet-50 via-white to-pink-50 p-6 text-center shadow-[0_6px_0_#e5e7eb] sm:p-10"><div className="mb-2 text-5xl">🎒</div><h1 className="text-4xl font-black text-slate-900 sm:text-6xl">שלום, כיתה א׳!</h1><p className="mx-auto mt-3 max-w-2xl text-lg text-slate-600">תרגול צבעוני לילדים, להורים ולמורים — בוחרים לשונית ומתחילים.</p></header><nav aria-label="מודולי תרגול" className="no-print my-7 grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-6">{MODULES.map(([id,emoji,title])=><button key={id} onClick={()=>selectModule(id)} aria-controls="first-grade-activity" aria-pressed={module===id} className={`rounded-3xl border-2 p-4 text-right transition hover:-translate-y-1 ${module===id?'border-violet-500 bg-violet-50 shadow-[0_4px_0_#8b5cf6]':'border-slate-200 bg-white'}`}><span className="text-3xl">{emoji}</span><b className="mt-2 block text-base sm:text-lg">{title}</b><small className="mt-1 block text-slate-500">פעילות אינטראקטיבית</small></button>)}</nav><section id="first-grade-activity" ref={activityRef} tabIndex={-1} aria-label={active[2]} style={{scrollMarginTop: 16}} className="mx-auto max-w-5xl outline-none rounded-[32px] border-2 border-slate-200 bg-white p-5 shadow-[0_7px_0_#dce1ee] sm:p-8"><div className="mb-6 flex flex-wrap items-center justify-between gap-3"><div><p className="text-sm font-bold text-violet-600">מודול נבחר</p><h2 className="text-3xl font-black">{active[1]} {active[2]}</h2></div><button onClick={()=>window.print()} className="no-print rounded-2xl bg-slate-900 px-5 py-3 font-bold text-white">🖨️ הדפסת דף</button></div>{module==='letters'&&<Letters size={size} setSize={setSize} trace={trace} setTrace={setTrace}/>} {module==='clock'&&<Clock hour={clock} setHour={setClock}/>} {module==='math'&&<MathGame equation={equation} options={options} answer={answer} setAnswer={setAnswer} level={mathLevel} setLevel={setMathLevel} score={score} setScore={setScore} next={()=>{setRound(r=>r+1);setAnswer(null)}}/>} {module==='reading'&&<Reading/>} {module==='english'&&<English/>} {module==='months'&&<Months month={month} setMonth={setMonth}/>}</section><div className="no-print mt-10"><SeoBody paragraphs={firstGradeBody} faq={firstGradeFaq} related={firstGradeRelated} /></div></div>
}

// Hebrew uses the single-line dashed tracing font (one line per stroke, no
// overlapping outlines); anything else falls back to a dashed outline.
function TraceText({value,repeats:want=1,stroke='#94a3b8',height=150}){
  const base=want===1?104:58
  const heb=/[\u0590-\u05FF]/.test(value)
  // Long words get fewer copies per row instead of overlapping each other.
  const copyW=[...value].length*0.62*base*(heb?1.2:1)
  const repeats=want===1?1:Math.max(1,Math.min(want,Math.floor(900/(copyW+60))))
  const positions=repeats===1?[500]:Array.from({length:repeats},(_,i)=>900-i*(800/(repeats-1)))
  const room=repeats===1?900:800/(repeats-1)*0.9
  const fs=heb?Math.min(base*1.2,room/Math.max([...value].length*0.62,1)):base
  // Writing lines: the letters sit on the baseline and reach exactly the top line.
  const y=height*0.8, top=y-(heb?0.6:0.72)*fs
  return <svg viewBox={`0 0 1000 ${height}`} className="block h-full w-full" role="img" aria-label={`תרגול כתיבה: ${value}`}>
    <path d={`M10 ${top} H990`} stroke="#bfdbfe" strokeWidth="2" strokeDasharray="10 8"/>
    <path d={`M10 ${y} H990`} stroke="#93c5fd" strokeWidth="2.5"/>
    {positions.map((x,i)=>heb
      ?<text key={i} x={x} y={y} textAnchor="middle" direction="rtl" fontFamily="BugaTracer" fontSize={fs} fill={stroke} stroke={stroke} strokeWidth={fs*0.014}>{value}</text>
      :<text key={i} x={x} y={y} textAnchor="middle" direction="rtl" unicodeBidi="plaintext" fontFamily="Arial, sans-serif" fontSize={fs} fontWeight="700" fill="none" stroke={stroke} strokeWidth="2.2" strokeDasharray="4 5" strokeLinecap="round">{value}</text>)}
  </svg>
}
// Hollow letters to colour in — white fill over the stroke leaves only the outer contour.
function ColorWord({value}){
  const fs=Math.min(130,900/Math.max([...value].length*0.62,1))
  return <svg viewBox="0 0 1000 170" className="block h-full w-full" role="img" aria-label={`צביעה: ${value}`}>
    <text x="500" y="130" textAnchor="middle" direction="rtl" fontFamily="Heebo, Arial, sans-serif" fontWeight="800" fontSize={fs} fill="white" stroke="#111" strokeWidth="6" strokeLinejoin="round" paintOrder="stroke">{value}</text>
  </svg>
}
function Letters({size,setSize,trace,setTrace}){
  const [color,setColor]=useState('#64748b'),value=trace||'אבא',repeatCount=size==='large'?3:size==='medium'?4:5
  return <section className="rounded-3xl bg-pink-50 p-5 text-center">
    <div className="no-print flex flex-wrap items-center justify-center gap-3"><label className="font-bold">כתבו אות או מילה<input value={trace} onChange={e=>setTrace(e.target.value.slice(0,12))} placeholder="למשל: אבא" className="mr-2 rounded-xl border-2 p-3"/></label><label className="font-bold">גודל<select value={size} onChange={e=>setSize(e.target.value)} className="mr-2 rounded-xl border-2 p-3"><option value="small">קטן</option><option value="medium">בינוני</option><option value="large">גדול</option></select></label></div>
    <p className="mt-5 text-slate-600">עוברים בעיפרון על הקו המקווקו, כותבים לבד בשורות, ובסוף צובעים.</p>
    <div className="mx-auto my-5 max-w-3xl bg-white p-4 sm:p-6">
      <div className="h-32 print:h-28"><TraceText value={value} stroke={color}/></div>
      <div className="h-32 print:h-28"><TraceText value={value} stroke={color}/></div>
      <div className="mt-3 grid gap-1">{[1,2,3,4].map(i=><div key={i} className={`h-20 print:h-16 ${i===4?'print:hidden':''}`}><TraceText value={value} repeats={repeatCount} stroke="#b6c0ce" height={80}/></div>)}</div>
      <p className="mt-6 text-lg font-bold print:mt-2">צובעים את {[...value].length>1?'המילה':'האות'}</p>
      <div className="h-40 print:h-32"><ColorWord value={value}/></div>
    </div>
    <div className="no-print flex justify-center gap-2 text-3xl" aria-label="צבע קו המתאר">{['#64748b','#ef4444','#f59e0b','#16a34a','#2563eb','#9333ea'].map(c=><button key={c} onClick={()=>setColor(c)} style={{color:c}} aria-label={`צבע ${c}`} className={color===c?'rounded-full ring-2 ring-slate-700':''}>●</button>)}</div>
  </section>
}
function Clock({hour,setHour}){const [minute,setMinute]=useState(0);const presets=['07:00','08:30','10:15','12:00','13:45','16:20','18:30','20:00'];const setTime=value=>{const [h,m]=value.split(':').map(Number);setHour(h);setMinute(m)};const hourDeg=(hour%12)*30+minute*.5,minuteDeg=minute*6;return <section className="rounded-3xl bg-emerald-50 p-4 text-center sm:p-6"><div className="mb-5 rounded-2xl bg-slate-900 p-4 text-white"><p className="text-sm text-sky-200">השעון הדיגיטלי שלי</p><div className="text-4xl font-black tracking-wider text-sky-300" dir="ltr">{fmt(hour)}:{fmt(minute)}</div></div><div className="mb-5 rounded-2xl bg-white p-4"><p className="mb-3 font-bold">🕐 שעות מוכנות לבחירה</p><div className="flex flex-wrap justify-center gap-2">{presets.map(value=><button key={value} onClick={()=>setTime(value)} className={`rounded-full px-4 py-2 font-bold ${value===`${fmt(hour)}:${fmt(minute)}`?'bg-orange-500 text-white':'bg-amber-100'}`} dir="ltr">{value}</button>)}</div><div className="mt-3 flex flex-wrap justify-center gap-2"><span className="px-2 py-2 font-bold">דקות:</span>{[0,5,10,15,20,30,45].map(m=><button key={m} onClick={()=>setMinute(m)} className={`rounded-full border-2 px-3 py-1 font-bold ${minute===m?'border-sky-500 bg-sky-100':'bg-white'}`} dir="ltr">{fmt(m)}</button>)}</div></div><div className="relative mx-auto size-72 rounded-full border-8 border-orange-400 bg-white shadow-inner sm:size-96"><div className="absolute inset-5 rounded-full border-2 border-dashed border-orange-200"/>{Array.from({length:12},(_,i)=><span key={i} className="absolute left-1/2 top-2 -translate-x-1/2 font-black sm:text-xl" style={{transform:`rotate(${i*30}deg) translateY(105px) rotate(-${i*30}deg)`}}>{i||12}</span>)}<span className="absolute left-1/2 top-1/2 h-28 w-2 origin-bottom -translate-x-1/2 -translate-y-full rounded-full bg-blue-500" style={{transform:`translateX(-50%) rotate(${minuteDeg}deg)`,transformOrigin:'bottom'}}/><span className="absolute left-1/2 top-1/2 h-20 w-3 origin-bottom -translate-x-1/2 -translate-y-full rounded-full bg-orange-500" style={{transform:`translateX(-50%) rotate(${hourDeg}deg)`,transformOrigin:'bottom'}}/><span className="absolute left-1/2 top-1/2 size-5 -translate-x-1/2 -translate-y-1/2 rounded-full bg-slate-900"/></div><p className="mt-4 text-slate-600">בחרו שעה ודקות ולמדו לקרוא את המחוגים.</p></section>}
function MathGame({equation,options,answer,setAnswer,level,setLevel,score,setScore,next}){const emoji=MATH_EMOJIS[(equation.a+equation.b)%MATH_EMOJIS.length];function choose(v){setAnswer(v);if(v===equation.correct)setScore(s=>s+1)}return <section className="rounded-3xl bg-amber-50 p-5 text-center"><div className="mb-4 flex flex-wrap justify-center gap-2">{[['easy','קל עד 10'],['medium','בינוני עד 15'],['hard','קשה עד 20']].map(([id,label])=><button key={id} onClick={()=>{setLevel(id);setAnswer(null)}} className={`rounded-xl border-2 px-4 py-2 font-bold ${level===id?'border-pink-500 bg-pink-100':'bg-white'}`}>{label}</button>)}</div><p className="text-sm text-slate-600">ניקוד: {score}</p><div className="my-4 text-5xl font-black" dir="ltr">{equation.a} + {equation.b} = ?</div><div className="mx-auto mb-6 max-w-xl rounded-2xl border-2 border-slate-200 bg-white p-4"><p className="mb-2 text-sm font-bold text-slate-600">אפשר לספור את החפצים</p><div className="flex flex-wrap justify-center gap-1 text-3xl" aria-label={`${equation.a} ${emoji}`}>‎{Array.from({length:equation.a},(_,i)=><span key={`a-${i}`}>{emoji}</span>)}<b className="px-2 text-2xl">+</b>{Array.from({length:equation.b},(_,i)=><span key={`b-${i}`}>{emoji}</span>)}</div></div><div className="grid grid-cols-2 gap-3 sm:grid-cols-4" dir="ltr">{options.map(v=><button key={v} onClick={()=>choose(v)} className={`rounded-2xl border-2 p-4 text-2xl font-black ${answer!==null?(v===equation.correct?'border-green-500 bg-green-100':'border-slate-200 bg-white'):'border-slate-200 bg-white hover:bg-violet-50'}`}>{v}</button>)}</div>{answer!==null&&<div className="mt-5 text-xl font-bold">{answer===equation.correct?'✅ תשובה נכונה!':'❌ נסו שוב'}</div>}<button onClick={next} className="mt-5 rounded-xl bg-violet-600 px-5 py-3 font-bold text-white">תרגיל חדש ↻</button></section>}
function Reading(){const [target,setTarget]=useState(WORDS[0][0]),[chosen,setChosen]=useState(null);const item=WORDS.find(x=>x[0]===target);function speak(){if('speechSynthesis' in window){window.speechSynthesis.cancel();window.speechSynthesis.speak(new SpeechSynthesisUtterance(`מצאו את המילה ${target}`))}}return <section className="rounded-3xl bg-blue-50 p-5 text-center"><div className="flex flex-wrap items-center justify-center gap-3"><p className="text-lg">מצאו את המילה שההורה בחר:</p><button onClick={speak} className="rounded-xl bg-violet-600 px-4 py-2 font-bold text-white">🔊 השמיעו</button></div><div className="my-3 text-3xl font-black">{item[1]} {target}</div><div className="grid grid-cols-2 gap-3 sm:grid-cols-3">{WORDS.map(([word,emoji])=><button key={word} onClick={()=>setChosen(word)} className={`rounded-2xl border-2 bg-white p-5 text-xl font-bold ${chosen===word?(word===target?'border-green-500 bg-green-100':'border-red-400 bg-red-50'):''}`}>{emoji}<br/>{word}</button>)}</div>{chosen&&<p className="mt-4 text-xl font-bold">{chosen===target?'✅ מצוין!':'❌ נסו שוב'}</p>}<button onClick={()=>{setTarget(WORDS[(WORDS.findIndex(x=>x[0]===target)+1)%WORDS.length][0]);setChosen(null)}} className="mt-5 rounded-xl bg-violet-600 px-5 py-3 font-bold text-white">מילה חדשה ↻</button></section>}
function English(){
  const [index,setIndex]=useState(0),[chosen,setChosen]=useState(null),[mode,setMode]=useState('words')
  const current=ENGLISH_WORDS[index]
  const choicePool=[current,...ENGLISH_WORDS.filter((_,i)=>i!==index)].slice(0,4)
  const choices=choicePool.map((_,i)=>choicePool[(i+index%4)%4])
  const letters=['A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z']
  function speak(text){if('speechSynthesis' in window){window.speechSynthesis.cancel();const voice=new SpeechSynthesisUtterance(text);voice.lang='en-US';voice.rate=.75;window.speechSynthesis.speak(voice)}}
  function next(){setIndex(i=>(i+1)%ENGLISH_WORDS.length);setChosen(null)}
  return <section className="rounded-3xl bg-cyan-50 p-4 text-center sm:p-6" dir="rtl">
    <div className="no-print mb-5 flex justify-center gap-2"><button onClick={()=>setMode('words')} className={`rounded-xl border-2 px-4 py-2 font-bold ${mode==='words'?'border-cyan-500 bg-cyan-100':'bg-white'}`}>🖼️ מילים ראשונות</button><button onClick={()=>setMode('letters')} className={`rounded-xl border-2 px-4 py-2 font-bold ${mode==='letters'?'border-cyan-500 bg-cyan-100':'bg-white'}`}>🔤 אותיות A–Z</button></div>
    {mode==='words'?<><p className="text-lg font-bold">איזו מילה מתאימה לתמונה?</p><div className="my-4 text-7xl">{current[2]}</div><button onClick={()=>speak(current[0])} className="no-print mb-5 rounded-xl bg-cyan-600 px-5 py-3 font-bold text-white">🔊 הקשיבו למילה</button><div className="grid grid-cols-2 gap-3 sm:grid-cols-4" dir="ltr">{choices.map(([word,hebrew])=><button key={word} onClick={()=>setChosen(word)} className={`rounded-2xl border-2 bg-white p-4 text-xl font-black ${chosen===word?(word===current[0]?'border-green-500 bg-green-100':'border-red-400 bg-red-50'):''}`}><span>{word}</span><small className="mt-1 block font-normal text-slate-500" dir="rtl">{hebrew}</small></button>)}</div>{chosen&&<p className="mt-4 text-xl font-bold" aria-live="polite">{chosen===current[0]?'✅ Excellent! כל הכבוד':'❌ נסו שוב'}</p>}<button onClick={next} className="no-print mt-5 rounded-xl bg-violet-600 px-5 py-3 font-bold text-white">מילה חדשה ↻</button></>:<><p className="mb-4 text-lg font-bold">לחצו על אות כדי לשמוע אותה</p><div className="grid grid-cols-5 gap-2 sm:grid-cols-9" dir="ltr">{letters.map(letter=><button key={letter} onClick={()=>speak(letter)} className="aspect-square rounded-2xl border-2 border-cyan-200 bg-white text-2xl font-black text-slate-900 shadow-[0_3px_0_#bae6fd] hover:-translate-y-1 hover:bg-yellow-50">{letter}</button>)}</div></>}
  </section>
}
function Months({month,setMonth}){const selected=MONTHS.find(x=>x[0]===month);function speak(name){if('speechSynthesis' in window){window.speechSynthesis.cancel();window.speechSynthesis.speak(new SpeechSynthesisUtterance(name))}}return <section className="rounded-3xl bg-violet-50 p-4 sm:p-6"><div className="mb-5 flex flex-wrap items-center justify-between gap-2"><div><p className="text-sm font-bold text-violet-700">לוח השנה שלי</p><h3 className="text-2xl font-black">בחרו חודש ולמדו עליו</h3></div><span className="rounded-full bg-white px-4 py-2 font-bold text-violet-700">12 חודשים · 4 עונות</span></div><div className="grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-4">{MONTHS.map(([name,emoji,season,days])=><article key={name} className={`rounded-2xl border-2 bg-white p-4 text-center shadow-[0_3px_0_#e4ddf7] transition hover:-translate-y-1 ${month===name?'border-pink-500 bg-pink-50 shadow-[0_3px_0_#ec4899]':'border-slate-200'}`}><button onClick={()=>setMonth(name)} className="w-full font-bold"><span className="text-4xl">{emoji}</span><strong className="mt-2 block text-2xl">{name}</strong><span className="mt-1 inline-block rounded-full bg-slate-100 px-3 py-1 text-sm">{season} · {days} ימים</span></button><button onClick={()=>speak(name)} className="mt-3 rounded-xl border border-slate-200 px-3 py-1 text-sm font-bold" aria-label={`השמיעו את ${name}`}>🔊 השמיעו</button></article>)}</div>{selected&&<div className="mt-6 rounded-2xl border-2 border-pink-200 bg-white p-4 text-center" aria-live="polite"><p className="text-xl font-black">📅 בחרתם בחודש {selected[0]}</p><p className="mt-1 text-slate-600">הוא בחודשי {selected[2]} ויש בו בדרך כלל {selected[3]} ימים.</p><button onClick={()=>speak(`חודש ${selected[0]}, עונת ${selected[2]}`)} className="mt-3 rounded-xl bg-violet-600 px-5 py-2 font-bold text-white">🔊 הקשיבו לחודש</button></div>}</section>}
