import { useEffect, useState } from 'react'
import { supabase } from '../utils/supabase'
import SEO from '../components/ui/SEO'

const OWNER_EMAIL = 'yos300@gmail.com'
export default function OwnerLogin({ children }){
  const [session,setSession]=useState(undefined),[email,setEmail]=useState(OWNER_EMAIL),[password,setPassword]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[sent,setSent]=useState(false)
  useEffect(()=>{let active=true;supabase.auth.getSession().then(({data})=>active&&setSession(data.session));const {data:{subscription}}=supabase.auth.onAuthStateChange((_event,next)=>setSession(next));return()=>{active=false;subscription.unsubscribe()}},[])
  if(session?.user?.email?.toLowerCase()===OWNER_EMAIL)return children
  async function login(event){event.preventDefault();setBusy(true);setError('');const {data,error}=await supabase.auth.signInWithPassword({email:email.trim().toLowerCase(),password});if(error||data.user?.email?.toLowerCase()!==OWNER_EMAIL){if(!error&&data.session)await supabase.auth.signOut();setError(error?.message||'החשבון הזה אינו חשבון הבעלים.');}setBusy(false)}
  async function reset(){setBusy(true);setError('');const {error}=await supabase.auth.resetPasswordForEmail(OWNER_EMAIL,{redirectTo:`${window.location.origin}/admin/login`});if(error)setError(error.message);else setSent(true);setBusy(false)}
  async function google(){setBusy(true);setError('');const {error}=await supabase.auth.signInWithOAuth({provider:'google',options:{redirectTo:`${window.location.origin}/admin/activity`}});if(error){setError(error.message);setBusy(false)}}
  return <div className="mx-auto max-w-md px-4 py-16" dir="rtl"><SEO title="כניסת בעלים" description="כניסה מאובטחת לדוח פעילות עוגה בוגה." noindex path="/admin/login"/><form onSubmit={login} className="rounded-3xl border-2 border-slate-200 bg-white p-7 shadow-[0_7px_0_#e5e7eb]"><p className="font-bold text-violet-600">עוגה בוגה · אזור בעלים</p><h1 className="mt-2 text-3xl font-black">כניסה לדוח הפעילות</h1><p className="mt-2 text-slate-600">הדוח זמין רק לחשבון הבעלים המאושר.</p><button type="button" onClick={google} disabled={busy} className="mt-6 w-full rounded-xl border-2 border-slate-300 bg-white px-5 py-3 font-bold text-slate-800 shadow-sm disabled:opacity-60">{busy?'מעבירים ל־Google…':'🌈 כניסה עם Google'}</button><div className="my-5 flex items-center gap-3 text-sm text-slate-400"><span className="h-px flex-1 bg-slate-200"/>או עם סיסמה<span className="h-px flex-1 bg-slate-200"/></div><label className="block font-bold">אימייל<input value={email} onChange={e=>setEmail(e.target.value)} type="email" autoComplete="email" className="mt-1 w-full rounded-xl border-2 p-3" required/></label><label className="mt-4 block font-bold">סיסמה<input value={password} onChange={e=>setPassword(e.target.value)} type="password" autoComplete="current-password" className="mt-1 w-full rounded-xl border-2 p-3" required/></label>{error&&<p role="alert" className="mt-4 rounded-xl bg-red-50 p-3 text-red-700">{error}</p>}{sent&&<p className="mt-4 rounded-xl bg-green-50 p-3 text-green-700">נשלח קישור לאיפוס סיסמה למייל.</p>}<button disabled={busy} className="mt-6 w-full rounded-xl bg-violet-600 px-5 py-3 font-bold text-white disabled:opacity-60">{busy?'נכנסים…':'כניסה עם סיסמה'}</button><button type="button" onClick={reset} disabled={busy} className="mt-3 w-full rounded-xl border-2 border-violet-200 px-5 py-3 font-bold text-violet-700">שכחתי סיסמה — שלחו לי קישור</button></form></div>
}
