import { useMemo, useState } from 'react'
import SEO from '../../components/ui/SEO'
import Breadcrumbs from '../../components/ui/Breadcrumbs'

const PACKS = [
  ['birthday','🎂','יום הולדת צבעוני','#ffe1ec',['👑 כתר יום הולדת','🎂 עוגת ענק','🎈 בלון לב','🥳 כובע מסיבה','🎁 מתנה נוצצת','🍭 סוכרייה','🕶️ משקפי מסיבה','🎀 פפיון','🎉 חגיגה!','⭐ כוכב היום','💖 לב גדול','🎊 קונפטי']],
  ['funny','🤪','מצחיקים ומוגזמים','#e5dcff',['🥸 שפם ענק','🤓 משקפיים מצחיקים','👄 שפתיים אדומות','👃 אף ליצן','😮 פה מופתע','👂 אוזניים גדולות','🎭 מסכה','🧠 מוח גאוני','💬 וואו!','😂 חחח','😎 הכי קול','🤩 איזה כיף']],
  ['fantasy','🦄','קסם ופנטזיה','#dff8f3',['🦄 חד-קרן','🧚 כנפיים','✨ שרביט קסמים','🌈 קשת','🐉 דרקון קטן','🧜 זנב בת ים','🔮 כדור בדולח','🌟 כוכב קסם','👑 כתר מלכותי','🪄 אברקדברה','💜 לב סגול','☁️ ענן חלום']],
  ['adventure','🚀','חלל והרפתקה','#dceeff',['🚀 טיל','👨‍🚀 קסדת חלל','🪐 שבתאי','👽 חייזר ידידותי','⭐ כוכב','🌙 ירח','🗺️ מפת אוצר','🏴‍☠️ דגל פיראטים','🔭 טלסקופ','💎 יהלום','🦖 דינוזאור','🔥 אמיץ/ה']],
  ['school','🏆','כיתה וסיום שנה','#fff1be',['🏆 אלוף/ה','📚 קורא/ת-על','✏️ כותב/ת','🧠 חכם/ה','🎓 סיום שנה','🫶 צוות מנצח','🌟 הצטיינות','🖍️ יוצר/ת','🎯 מטרה','🔢 אלוף/ת החשבון','🦸 גיבור/ת הכיתה','👏 כל הכבוד!']],
]
function parts(text){const i=text.indexOf(' ');return i>0?[text.slice(0,i),text.slice(i+1)]:['✨',text]}

export default function PhotoProps(){
  const [id,setId]=useState('birthday'),[eventName,setEventName]=useState(''),[printMode,setPrintMode]=useState('color')
  const pack=useMemo(()=>PACKS.find(x=>x[0]===id),[id]); const [,,title,color,props]=pack
  return <div className={`mx-auto max-w-7xl px-4 py-8 buga-fade-in ${printMode==='bw'?'photo-print-bw':''}`}><div className="no-print mx-auto mb-4 flex max-w-xl justify-center gap-2"><b>הדפסה:</b><button onClick={()=>setPrintMode('color')} className="rounded-xl border-2 bg-pink-100 px-4 py-2">🌈 צבעוני</button><button onClick={()=>setPrintMode('bw')} className="rounded-xl border-2 bg-slate-200 px-4 py-2">⚫ שחור־לבן</button></div>
    <SEO title="אביזרי צילום להדפסה" description="חבילות גדולות של אביזרי צילום ליום הולדת, כיתה, חלל, חד-קרן ומסיבה — להדפסה חינם." path="/printables/photo-props"/>
    <Breadcrumbs items={[{label:'ראשי',href:'/'},{label:'דפים להדפסה',href:'/printables'},{label:'אביזרי צילום'}]}/>
    <header className="text-center no-print"><h1 className="text-4xl sm:text-5xl">📸 אביזרי צילום גדולים להדפסה</h1><p className="mx-auto mt-3 max-w-2xl text-lg text-[var(--muted-foreground)]">בחרו חבילה, כתבו שם לאירוע אם רוצים, הדפיסו — וגזרו. בכל חבילה יש 12 אביזרים גדולים וברורים.</p></header>
    <section className="no-print mt-7 grid gap-4 sm:grid-cols-2 lg:grid-cols-5">{PACKS.map(x=><button key={x[0]} onClick={()=>setId(x[0])} className={`rounded-3xl border-2 p-5 text-right transition hover:-translate-y-1 ${x[0]===id?'border-[var(--ink)] ring-4 ring-black/10':'border-slate-200'}`} style={{background:x[3]}}><span className="text-4xl">{x[1]}</span><b className="mt-3 block text-xl">{x[2]}</b><small>12 אביזרים גדולים</small></button>)}</section>
    <div className="no-print mx-auto mt-6 flex max-w-2xl flex-col gap-3 rounded-3xl border-2 border-[var(--border)] bg-white p-5 sm:flex-row sm:items-end"><label className="flex-1 font-bold">כותרת אישית לחבילה (אופציונלי)<input value={eventName} onChange={e=>setEventName(e.target.value)} placeholder="למשל: יום ההולדת של נועה" className="mt-1 w-full rounded-xl border-2 border-[var(--border)] px-3 py-2 font-normal"/></label><button onClick={()=>window.print()} className="wobbly-md sketch-press border-[3px] border-[var(--border)] bg-[var(--accent)] px-6 py-3 text-xl font-bold text-white">🖨️ הדפיסו חבילה</button></div>
    <article className="photo-props-sheet mt-8 bg-white p-5 sm:p-8" style={{'--pack-color':color}}><header className="photo-props-heading"><span>{pack[1]}</span><div><small>עוגה בוגה · אביזרי צילום להדפסה</small><h2>{eventName||title}</h2><p>גזרו מסביב לקו המקווקו והדביקו למקל</p></div></header><div className="photo-props-grid">{props.map((value,i)=>{const [emoji,label]=parts(value);return <div className="photo-prop" key={value}><div className="prop-stick"/><div className="prop-cut"><span>{emoji}</span><strong>{label}</strong><small>גזרו כאן ✂</small></div><i>{i+1}</i></div>})}</div><footer>ugabuga.co.il · הדפסה לשימוש אישי וחינוכי</footer></article>
    <style>{`.photo-props-sheet{max-width:1120px;margin-inline:auto;border:3px solid #1d263b;border-radius:25px;box-shadow:0 8px 0 #1d263b}.photo-props-heading{display:flex;align-items:center;justify-content:center;gap:16px;text-align:center;border-bottom:3px dashed #1d263b;padding:0 0 18px}.photo-props-heading>span{font-size:54px}.photo-props-heading h2{font-size:clamp(28px,4vw,46px);margin:2px 0}.photo-props-heading p{margin:0;color:#526075}.photo-props-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:18px;margin-top:24px}.photo-prop{position:relative;min-height:205px;display:flex;justify-content:center}.prop-cut{position:relative;z-index:2;display:flex;min-height:155px;width:100%;flex-direction:column;align-items:center;justify-content:center;border:3px dashed #222;border-radius:28px;background:linear-gradient(145deg,var(--pack-color),white 75%);padding:15px;text-align:center}.prop-cut span{font-size:56px;line-height:1}.prop-cut strong{font-size:clamp(17px,2vw,24px);margin-top:7px}.prop-cut small{font-size:11px;margin-top:6px;color:#64748b}.prop-stick{position:absolute;z-index:1;bottom:0;width:13px;height:60px;border:2px solid #764d2c;border-radius:0 0 8px 8px;background:#e9b785}.photo-prop i{position:absolute;z-index:3;top:8px;right:10px;border-radius:50%;background:white;padding:2px 8px;font-size:11px;font-style:normal}.photo-props-sheet footer{margin-top:20px;text-align:center;font-size:12px;color:#64748b}@media(max-width:640px){.photo-props-grid{grid-template-columns:repeat(2,1fr);gap:10px}.photo-prop{min-height:175px}.prop-cut{min-height:130px;padding:8px}.prop-cut span{font-size:44px}.prop-stick{height:48px}.photo-props-heading>span{font-size:42px}}@media print{.no-print,header.site-header,footer:not(.photo-props-sheet footer){display:none!important}.photo-props-sheet{border:0!important;box-shadow:none!important;margin:0!important;padding:0!important}.photo-props-heading{padding-bottom:9px}.photo-props-grid{gap:10px;margin-top:10px}.photo-prop{min-height:155px}.prop-cut{min-height:120px}.prop-cut span{font-size:42px}.prop-stick{height:40px}.photo-props-sheet footer{display:block!important;margin-top:8px}}`}</style>
  </div>
}
