import { useEffect, useMemo, useRef, useState } from 'react'
import { Link, useParams } from 'react-router-dom'
import SEO from '../components/ui/SEO'
import SeoBody, { faqSchema } from '../components/ui/SeoBody'
import Breadcrumbs from '../components/ui/Breadcrumbs'
import PrintPreview from '../components/ui/PrintPreview'
import NotFound from '../pages/NotFound'
import {
  GRADES, STAGES, gradeInfo, parseGradeParam, topicsFor, findTopic, topicsByStrand, topicPath,
  makeExercise, makeLevelExercise, makeWorksheet, makeTest, STRANDS,
} from './registry'
import { checkAnswer, formatAnswer, isBlank } from './check'
import '../learn/learn.css'
import './math.css'

const HOME = { label: 'ראשי', href: '/' }
const HUB = { label: 'מתמטיקה', href: '/math' }
const gradeCrumb = g => ({ label: `כיתה ${g.label}`, href: g.path })
const newSeed = () => Math.floor(Math.random() * 2 ** 31) + 1
// Stable per-page seed so the prerendered first exercise matches the one rendered on hydration.
const pageSeed = s => { let h = 2166136261; for (const c of s) h = Math.imul(h ^ c.charCodeAt(0), 16777619); return (h >>> 0) || 1 }
const Chip = ({ on, onClick, children, ...rest }) => <button type="button" className="ln-chip" aria-pressed={on} onClick={onClick} {...rest}>{children}</button>

// ── math inside Hebrew text ───────────────────────────────
// Runs like "7 + 8 = 15" or "x = −3" are isolated as LTR so the bidi algorithm doesn't reorder them.
const MATH_RUN = /(?:(?<![֐-׿])-|[−(√π?☐0-9a-zA-Z])[0-9a-zA-Z.,/()+\-−×÷=<>≤≥≠±²³√π:^·|?☐° ]*[0-9a-zA-Z)²³π?☐°]|[0-9a-zA-Z?]/g
// Cut a run at the first ")" that closes nothing (e.g. "5): 5/6" → "5"), and drop a trailing "(" opener.
function balancedLength(run) {
  let depth = 0
  for (let i = 0; i < run.length; i++) {
    if (run[i] === '(') depth++
    else if (run[i] === ')') { if (!depth) return i; depth-- }
  }
  if (!depth) return run.length
  const lastOpen = run.lastIndexOf('(')
  return lastOpen > 0 ? lastOpen : run.length
}
export function MathText({ children, as: Tag = 'span', className }) {
  const text = String(children ?? '')
  const out = []
  const re = new RegExp(MATH_RUN.source, 'g')
  let last = 0, k = 0, m
  while ((m = re.exec(text))) {
    const core = m[0].slice(0, balancedLength(m[0])).replace(/\s+$/, '')
    if (!core) { re.lastIndex = m.index + 1; continue }
    re.lastIndex = m.index + core.length
    if (m.index > last) out.push(text.slice(last, m.index))
    out.push(/[+\-−×÷=<>≤≥≠/^]|\d\s+\d|,\s*\d/.test(core) && /[\d?a-zA-Z]/.test(core) ? <bdi key={k++} dir="ltr" className="mth-ltr">{core}</bdi> : core)
    last = m.index + core.length
  }
  if (last < text.length) out.push(text.slice(last))
  return <Tag className={className}>{out}</Tag>
}

const Svg = ({ svg, className = 'mth-svg' }) => svg ? <div className={className} dangerouslySetInnerHTML={{ __html: svg }} /> : null // generated by our own code only

function Expr({ ex, big = true }) {
  return <>
    <MathText as="p" className="mth-q">{ex.q}</MathText>
    {ex.expr && <p className={big ? 'mth-expr' : 'mth-expr is-small'} dir="ltr">{ex.expr}</p>}
    <Svg svg={ex.svg} />
  </>
}

// ── answer input ───────────────────────────────
function AnswerInput({ ex, value, onChange, onSubmit, disabled, idPrefix = 'ans', autoFocus, state }) {
  const ref = useRef(null)
  useEffect(() => { if (autoFocus && ref.current && !disabled) ref.current.focus({ preventScroll: true }) }, [autoFocus, disabled, ex])
  if (ex.type === 'choice') {
    return <div className="mth-choices" role="group" aria-label="בחירת תשובה">
      {ex.choices.map(c => {
        const picked = value === c
        const cls = state && (c === String(ex.answer) ? 'is-right' : picked ? 'is-wrong' : '')
        return <button key={c} type="button" className={`mth-choice ${picked ? 'is-picked' : ''} ${cls || ''}`} aria-pressed={picked} disabled={disabled} onClick={() => { onChange(c); onSubmit?.(c) }}><MathText>{c}</MathText></button>
      })}
    </div>
  }
  const kb = ex.type === 'number' ? 'decimal' : 'text'
  const extraKeys = ex.type === 'fraction' ? ['/', '−', ' '] : ex.type === 'numbers' ? [',', '−', '/'] : ex.type === 'number' ? [...(ex.grade >= 6 ? ['−'] : []), ...(ex.grade >= 5 ? ['.'] : [])] : []
  const hint = ex.type === 'fraction' ? 'למשל 3/4 או 1 1/2' : ex.type === 'numbers' ? 'מפרידים בפסיק, למשל 2, −3' : ''
  const press = k => { const v = (value || '') + k; onChange(v); ref.current?.focus() }
  return <div className="mth-input-row">
    <label className="sr-only" htmlFor={`${idPrefix}-in`}>התשובה שלך</label>
    <input id={`${idPrefix}-in`} ref={ref} className={`mth-input ${state || ''}`} dir="ltr" inputMode={kb} autoComplete="off" autoCorrect="off" spellCheck="false" enterKeyHint="done"
      value={value || ''} disabled={disabled} placeholder="?" onChange={e => onChange(e.target.value)}
      onKeyDown={e => { if (e.key === 'Enter') { e.preventDefault(); onSubmit?.(value) } }} />
    {ex.unit && <span className="mth-unit">{ex.unit}</span>}
    {!disabled && extraKeys.length > 0 && <span className="mth-keys">{extraKeys.map(k => <button key={k} type="button" onClick={() => press(k)} aria-label={k === ' ' ? 'רווח' : k === '−' ? 'מינוס' : k === '/' ? 'קו שבר' : k}>{k === ' ' ? '␣' : k}</button>)}</span>}
    {hint && <small className="mth-hint">{hint}</small>}
  </div>
}

// ── practice: one exercise at a time, endless ───────────────────────────────
function Practice({ topic, level }) {
  // The first exercise comes from a stable seed (prerendered HTML = hydrated HTML); later ones are random.
  const key = `${topic.grade}/${topic.slug}/${level}`
  const [cur, setCur] = useState(() => ({ key, ex: makeLevelExercise(topic, level, pageSeed(key)) }))
  const [value, setValue] = useState('')
  const [result, setResult] = useState(null) // null | 'right' | 'wrong'
  const [score, setScore] = useState({ right: 0, total: 0, streak: 0, best: 0 })
  const nextRef = useRef(null)
  // Level changed: a new exercise that only this level has (never one the easier level also shows).
  if (cur.key !== key) { setCur({ key, ex: makeLevelExercise(topic, level, newSeed()) }); setValue(''); setResult(null) }
  const ex = cur.ex
  useEffect(() => { if (result) nextRef.current?.focus({ preventScroll: true }) }, [result])
  const submit = v => {
    if (result || isBlank(v ?? value)) return
    const ok = checkAnswer(ex, v ?? value)
    setResult(ok ? 'right' : 'wrong')
    setScore(s => { const streak = ok ? s.streak + 1 : 0; return { right: s.right + (ok ? 1 : 0), total: s.total + 1, streak, best: Math.max(s.best, streak) } })
  }
  const next = () => {
    let n
    for (let i = 0; i < 5; i++) { n = makeExercise(topic, level, newSeed()); if (n.q !== ex.q || n.expr !== ex.expr || n.svg !== ex.svg) break }
    setCur({ key, ex: n }); setValue(''); setResult(null)
  }
  return <section className="ln-box mth-card" aria-labelledby="practice-h">
    <div className="mth-score" aria-live="polite">
      <h2 id="practice-h" className="text-xl font-black m-0">✏️ תרגול</h2>
      <span>✅ {score.right}/{score.total}</span>
      <span title="תשובות נכונות ברצף">🔥 רצף {score.streak}{score.best > 1 ? ` (שיא ${score.best})` : ''}</span>
    </div>
    <div className={`mth-ex ${result === 'right' ? 'flash-ok' : result === 'wrong' ? 'flash-no' : ''}`}>
      <Expr ex={ex} />
      <AnswerInput ex={ex} value={value} onChange={setValue} onSubmit={submit} disabled={!!result} state={result === 'right' ? 'is-right' : result === 'wrong' ? 'is-wrong' : ''} />
    </div>
    {!result && ex.type !== 'choice' && <div className="mth-actions"><button type="button" className="ln-btn go" onClick={() => submit()} disabled={isBlank(value)}>בדיקה ✓</button></div>}
    {result && <div className={`mth-feedback ${result}`} role="status">
      <p className="mth-verdict">{result === 'right' ? '✓ נכון, כל הכבוד!' : <>✗ לא בדיוק. התשובה הנכונה: <bdi dir="ltr" className="mth-ltr">{formatAnswer(ex)}</bdi>{ex.unit ? ` ${ex.unit}` : ''}</>}</p>
      <MathText as="p" className="mth-explain">{ex.explain}</MathText>
      <button ref={nextRef} type="button" className="ln-btn go" onClick={next}>תרגיל הבא ←</button>
    </div>}
  </section>
}

// ── quiz: n questions, answers checked at the end ───────────────────────────────
const mmss = s => `${Math.floor(s / 60)}:${String(s % 60).padStart(2, '0')}`

function Quiz({ items, timer, onRestart, onPrint, title }) {
  const [i, setI] = useState(0)
  const [answers, setAnswers] = useState(() => items.map(() => ''))
  const [done, setDone] = useState(false)
  const [secs, setSecs] = useState(0)
  const t0 = useRef(0)
  useEffect(() => { t0.current = Date.now() }, [])
  useEffect(() => {
    if (!timer || done) return
    const id = setInterval(() => setSecs(Math.floor((Date.now() - t0.current) / 1000)), 500)
    return () => clearInterval(id)
  }, [timer, done])
  const set = v => setAnswers(a => a.map((x, k) => (k === i ? v : x)))
  const answered = answers.filter(a => !isBlank(a)).length
  const results = done ? items.map((ex, k) => checkAnswer(ex, answers[k])) : []
  const right = results.filter(Boolean).length
  const finish = () => { setSecs(Math.floor((Date.now() - t0.current) / 1000)); setDone(true); window.scrollTo?.({ top: 0, behavior: 'smooth' }) }
  if (done) {
    const pct = Math.round((right / items.length) * 100)
    return <section className="ln-box mth-card" aria-labelledby="quiz-res">
      <h2 id="quiz-res" className="text-3xl font-black text-center">{pct >= 90 ? '🏆' : pct >= 70 ? '🌟' : pct >= 50 ? '👍' : '💪'} {right} מתוך {items.length} — ציון {pct}</h2>
      {timer && <p className="text-center font-bold">⏱️ זמן: {mmss(secs)}</p>}
      <p className="text-center">{pct >= 90 ? 'מצוין! שולטים בחומר.' : pct >= 70 ? 'יפה מאוד! כדאי לעבור על הטעויות למטה.' : 'כדאי לעבור על ההסברים למטה ולתרגל עוד קצת.'}</p>
      <div className="mth-actions"><button type="button" className="ln-btn go" onClick={onRestart}>🔁 מבחן חדש</button>{onPrint && <button type="button" className="ln-btn alt" onClick={onPrint}>🖨️ הדפסת המבחן</button>}</div>
      <h3 className="mt-6 mb-2 text-xl font-black">סקירת התשובות</h3>
      <ol className="mth-review">{items.map((ex, k) => <li key={k} className={results[k] ? 'ok' : 'no'}>
        {ex.topicTitle && <small className="mth-tag">{ex.topicEmoji} {ex.topicTitle}</small>}
        <Expr ex={ex} big={false} />
        <p className="m-0"><b>{results[k] ? '✓' : '✗'}</b> התשובה שלך: <bdi dir="ltr" className="mth-ltr">{answers[k] || '—'}</bdi>{!results[k] && <> · התשובה הנכונה: <bdi dir="ltr" className="mth-ltr">{formatAnswer(ex)}</bdi>{ex.unit ? ` ${ex.unit}` : ''}</>}</p>
        {!results[k] && <MathText as="p" className="mth-explain">{ex.explain}</MathText>}
      </li>)}</ol>
    </section>
  }
  const ex = items[i]
  return <section className="ln-box mth-card" aria-label={title}>
    <div className="mth-score"><b>שאלה {i + 1} מתוך {items.length}</b><span>נענו {answered}</span>{timer && <span>⏱️ {mmss(secs)}</span>}</div>
    <div className="ln-bar my-2"><i style={{ width: `${((i + 1) / items.length) * 100}%` }} /></div>
    <div className="mth-dots" role="group" aria-label="מעבר לשאלה">{items.map((_, k) => <button key={k} type="button" className={`${k === i ? 'is-on' : ''} ${!isBlank(answers[k]) ? 'is-done' : ''}`} onClick={() => setI(k)} aria-label={`שאלה ${k + 1}`} aria-current={k === i}>{k + 1}</button>)}</div>
    <div className="mth-ex">
      {ex.topicTitle && <small className="mth-tag">{ex.topicEmoji} {ex.topicTitle}</small>}
      <Expr ex={ex} />
      <AnswerInput key={i} idPrefix={`q${i}`} ex={ex} value={answers[i]} onChange={set} autoFocus onSubmit={() => { if (i < items.length - 1) setI(i + 1) }} />
    </div>
    <div className="mth-actions">
      <button type="button" className="ln-btn alt" disabled={i === 0} onClick={() => setI(i - 1)}>→ הקודמת</button>
      {i < items.length - 1 ? <button type="button" className="ln-btn" onClick={() => setI(i + 1)}>הבאה ←</button>
        : <button type="button" className="ln-btn go" onClick={finish}>סיום ובדיקה ✓</button>}
    </div>
    {i < items.length - 1 && answered === items.length && <p className="text-center mt-3"><button type="button" className="underline font-bold" onClick={finish}>ענית על הכול — לסיום ובדיקה</button></p>}
  </section>
}

// ── printing ───────────────────────────────
function PrintItem({ ex }) {
  return <div className="mth-pitem">
    <MathText as="p" className="mth-pq">{ex.q}</MathText>
    {ex.expr && <p className="mth-pexpr" dir="ltr">{ex.expr}</p>}
    <Svg svg={ex.svg} className="mth-psvg" />
    {ex.type === 'choice'
      ? <p className="mth-pchoices">{ex.choices.map(c => <span key={c}>◯ <MathText>{c}</MathText></span>)}</p>
      : <p className="mth-pline">תשובה: <span /> {ex.unit || ''}</p>}
  </div>
}
function PrintSheets({ title, sub, items }) {
  return <>
    <article className="buga-flow mth-print" dir="rtl">
      <h2>{title}</h2>
      <p className="mth-pmeta"><span>שם: ____________</span><span>תאריך: ________</span><span>ציון: ____ / {items.length}</span></p>
      {sub && <p className="mth-psub">{sub}</p>}
      <ol className="mth-plist">{items.map((ex, k) => <li key={k}><PrintItem ex={ex} /></li>)}</ol>
    </article>
    <article className="buga-flow mth-print" dir="rtl">
      <h2>תשובות — {title}</h2>
      <ol className="mth-pkey">{items.map((ex, k) => <li key={k}><bdi dir="ltr">{formatAnswer(ex)}</bdi>{ex.unit ? ` ${ex.unit}` : ''}</li>)}</ol>
    </article>
  </>
}

// ── /math ───────────────────────────────
const HUB_FAQ = [
  { q: 'לאילו כיתות מתאים התרגול?', a: 'לכל שתים-עשרה שנות הלימוד: מכיתה א׳ ועד י״ב — יסודי, חטיבת ביניים ותיכון (3, 4 ו-5 יחידות לימוד). הנושאים מסודרים לפי כיתה ולפי תחום, בהתאם לתכנית הלימודים במתמטיקה של משרד החינוך.' },
  { q: 'האם התרגילים נגמרים?', a: 'לא. כל תרגיל נוצר מחדש בכל פעם, כך שאפשר לתרגל כמה שרוצים ולהדפיס כמה דפי עבודה שונים מאותו נושא — כל דף עם דף תשובות משלו.' },
  { q: 'מה ההבדל בין שלוש הרמות?', a: 'בכל נושא יש שלוש רמות קושי: הראשונה מתאימה למי שרק התחיל ללמוד את הנושא, השנייה לתרגול רגיל, והשלישית לאתגר ולהכנה למבחן. הרמה משנה את התחום של המספרים ואת סוג התרגילים.' },
  { q: 'צריך להירשם או לשלם?', a: 'לא. התרגול, המבחנים ודפי העבודה חינמיים לגמרי ופתוחים לכולם — בלי הרשמה ובלי להתקין דבר.' },
]

export function MathHub() {
  const [q, setQ] = useState('')
  const all = useMemo(() => GRADES.flatMap(g => topicsFor(g.n).map(t => ({ t, g }))), [])
  const term = q.trim()
  const hits = term.length >= 2 ? all.filter(({ t, g }) => `${t.title} ${g.label} כיתה ${g.label} ${STRANDS[t.strand]?.label || ''}`.includes(term)).slice(0, 24) : []
  return <div className="mx-auto max-w-6xl px-4 py-8 buga-fade-in" dir="rtl">
    <SEO title="מתמטיקה לכל הכיתות — תרגול, מבחנים ודפי עבודה מכיתה א׳ עד י״ב" description="מתמטיקה לפי כיתה, מכיתה א׳ עד י״ב: הסברים קצרים, תרגול אונליין בשלוש רמות, מבחנים מסכמים ודפי עבודה להדפסה עם תשובות. לפי תכנית הלימודים, חינם." path="/math" structuredData={faqSchema(HUB_FAQ)} />
    <Breadcrumbs items={[HOME, { label: HUB.label }]} />
    <header className="text-center">
      <span className="inline-flex rounded-full bg-sky-100 px-4 py-2 font-bold text-[#1d2233]">{all.length} נושאים · 12 כיתות · חינם</span>
      <h1 className="mt-3 text-4xl sm:text-5xl"><span aria-hidden="true">🧮 </span>מתמטיקה מכיתה א׳ עד י״ב</h1>
      <p className="mx-auto mt-2 max-w-2xl text-lg text-[var(--muted-foreground)]">בוחרים כיתה ונושא — ומקבלים הסבר קצר, דוגמה פתורה, תרגול בלי סוף בשלוש רמות, מבחן עם ציון ודף עבודה להדפסה עם דף תשובות.</p>
    </header>

    <div className="mx-auto mt-6 max-w-xl no-print">
      <label htmlFor="math-q" className="sr-only">חיפוש נושא</label>
      <input id="math-q" type="search" className="mth-search" value={q} onChange={e => setQ(e.target.value)} placeholder="חיפוש נושא: שברים, היקף, משוואות…" />
      {term.length >= 2 && <div className="mth-hits" aria-live="polite">{hits.length ? hits.map(({ t, g }) => <Link key={`${g.n}/${t.slug}`} to={topicPath(t)} className="ln-chip"><span aria-hidden="true">{t.emoji}</span> {t.title} · כיתה {g.label}</Link>) : <p className="m-0">לא נמצא נושא כזה. נסו מילה אחרת.</p>}</div>}
    </div>

    {STAGES.map(st => <section key={st.id} className="mt-10" aria-labelledby={`st-${st.id}`}>
      <h2 id={`st-${st.id}`} className="mb-4 text-2xl font-black">{st.label} <small className="text-base font-bold text-[var(--muted-foreground)]">· {st.range}</small></h2>
      <div className="grid gap-4 grid-cols-2 sm:grid-cols-3 lg:grid-cols-6">{st.grades.map(n => { const g = gradeInfo(n), c = topicsFor(n).length; return <Link key={n} to={g.path} className="wobbly card-lift border-2 border-[var(--border)] bg-[var(--card)] sketch-shadow p-4 text-center mth-grade-card">
        <span className="text-3xl" aria-hidden="true">{g.emoji}</span>
        <span className="block text-xl font-black">כיתה {g.label}</span>
        <small className="block text-[var(--muted-foreground)]">{c ? `${c} נושאים` : 'בקרוב'} · גילאי {g.ages}</small>
      </Link> })}</div>
    </section>)}

    <div className="mt-12"><SeoBody paragraphs={[
      'אזור המתמטיקה של עוגה בוגה בנוי לפי הכיתות ולפי תחומי הלימוד: מספרים ופעולות חשבון, שברים ומספרים עשרוניים, גאומטריה ומדידות, אלגברה, פונקציות, הסתברות וסטטיסטיקה — ובתיכון גם סדרות, טריגונומטריה וחשבון דיפרנציאלי ואינטגרלי. בכל נושא יש הסבר קצר בשפה פשוטה, טיפים לשיטת הפתרון ודוגמה פתורה צעד אחר צעד.',
      'אחרי ההסבר מתרגלים: תרגיל אחד בכל פעם, עם בדיקה מיידית, הסבר קצר לפתרון וספירת רצף של תשובות נכונות. במצב מבחן עונים על 10 שאלות ומקבלים ציון וסקירה של הטעויות רק בסוף, ובמבחן המסכם של כל כיתה השאלות מגיעות מכל הנושאים יחד. לכל נושא אפשר גם להדפיס דף עבודה של 20 תרגילים עם דף תשובות נפרד — מתאים להורים, למורים ולשיעורי בית.',
    ]} faq={HUB_FAQ} related={[{ label: 'אתגר לוח הכפל', href: '/learn/times-tables' }, { label: 'לוח הכפל', href: '/learn/multiplication-table' }, { label: 'דפי עבודה בחשבון', href: '/printables/math-worksheets' }, { label: 'דפי עבודה בשברים', href: '/printables/fractions-worksheets' }, { label: 'דפי עבודה בשעון', href: '/printables/clock-worksheets' }]} /></div>
  </div>
}

// ── /math/grade-N ───────────────────────────────
const GRADE_COPY = {
  1: 'בכיתה א׳ מכירים את המספרים — קודם עד 20 ואחר כך עד 100 — סופרים, משווים, מחברים ומחסרים, ומתחילים להכיר צורות.',
  2: 'בכיתה ב׳ מרחיבים את המספרים עד 1000, מחברים ומחסרים עם המרה, לומדים את משמעות הכפל והחילוק, ומודדים אורך וזמן.',
  3: 'בכיתה ג׳ מגיעים לרבבה (10,000), משלימים את לוח הכפל בעל פה, מחלקים עם שארית, מכירים שברים פשוטים ולומדים היקף וזוויות.',
  4: 'בכיתה ד׳ עובדים עם מספרים גדולים עד מיליון, כופלים במאונך ומחלקים בחילוק ארוך, מעמיקים בשברים ובגאומטריה של משולשים ומרובעים.',
  5: 'בכיתה ה׳ עוברים לשברים עם מכנים שונים ולמספרים עשרוניים, ממירים יחידות מידה ומחשבים שטחים של מצולעים.',
  6: 'בכיתה ו׳, האחרונה ביסודי, משלימים כפל וחילוק של שברים ומספרים עשרוניים, לומדים אחוזים, יחס וקנה מידה וממוצע, ומחשבים היקף מעגל, שטח עיגול ונפח תיבה.',
  7: 'בכיתה ז׳ מתחילה האלגברה: מספרים מכוונים, ביטויים אלגבריים ומשוואות ממעלה ראשונה, לצד יחס, אחוזים וגאומטריה של זוויות ומשולשים.',
  8: 'בכיתה ח׳ פותרים משוואות ואי-שוויונים, לומדים את הפונקציה הקווית ומערכות משוואות, ובגאומטריה — משפט פיתגורס וחפיפת משולשים.',
  9: 'בכיתה ט׳ לומדים כפל מקוצר ופירוק לגורמים, שברים אלגבריים, משוואה ריבועית ופרבולה, שורשים, דמיון משולשים, טריגונומטריה במשולש ישר זווית והסתברות.',
  10: 'בכיתה י׳ מתחיל המסלול לבגרות ב-3, 4 או 5 יחידות לימוד: משוואות ריבועיות, גאומטריה אנליטית, טריגונומטריה, הסתברות וסטטיסטיקה.',
  11: 'בכיתה י״א עוסקים בסדרות, בחשבון דיפרנציאלי — נגזרות, משיקים וחקירת פונקציות — ובנושאים נוספים לפי מספר יחידות הלימוד.',
  12: 'בכיתה י״ב מסיימים את חומר הבגרות: אינטגרלים וחישוב שטחים, פונקציות מעריכיות ולוגריתמיות, נגזרות של מנה והרכבה, ובמסלול 5 יחידות גם וקטורים, מספרים מרוכבים ואינדוקציה.',
}

function listHe(xs) { return xs.length < 2 ? xs.join('') : `${xs.slice(0, -1).join(', ')} ו${xs[xs.length - 1]}` }

export function MathGrade() {
  const n = parseGradeParam(useParams().gradeSlug)
  if (!n) return <NotFound />
  return <GradePage key={n} n={n} />
}

function GradePage({ n }) {
  const g = gradeInfo(n)
  const groups = topicsByStrand(n)
  const topics = topicsFor(n)
  const prev = gradeInfo(n - 1), next = gradeInfo(n + 1)
  const faq = [
    { q: `מה לומדים במתמטיקה בכיתה ${g.label}?`, a: `${GRADE_COPY[n]}${topics.length ? ` בעמוד הזה יש ${topics.length} נושאים: ${listHe(topics.map(t => t.title))}.` : ''}` },
    { q: `איך מתכוננים למבחן במתמטיקה בכיתה ${g.label}?`, a: `מתרגלים כל נושא בנפרד ברמה 2 ו-3, עוברים על ההסברים של הטעויות, ובסוף עושים את המבחן המסכם לכיתה ${g.label} — מבחן שמערבב שאלות מכל הנושאים, עם ציון וסקירה בסוף.` },
    { q: 'אפשר להדפיס דפי עבודה?', a: 'כן. בכל נושא יש כפתור הדפסה שמכין דף של 20 תרגילים ודף תשובות נפרד. בכל לחיצה על "תרגילים אחרים" מקבלים דף חדש. גם את המבחן המסכם אפשר להדפיס עם התשובות.' },
  ]
  const title = `מתמטיקה לכיתה ${g.label}`
  const desc = `מתמטיקה לכיתה ${g.label} (${g.stageLabel}): ${topics.length ? `${topics.length} נושאים לפי תכנית הלימודים` : 'נושאים לפי תכנית הלימודים'} עם הסבר, תרגול בשלוש רמות, מבחן מסכם ודפי עבודה להדפסה עם תשובות. חינם.`
  return <div className="mx-auto max-w-5xl px-4 py-8 buga-fade-in" dir="rtl">
    <SEO title={`${title} — נושאים, תרגול ומבחנים`} description={desc} path={g.path} structuredData={faqSchema(faq)} />
    <Breadcrumbs items={[HOME, HUB, { label: `כיתה ${g.label}` }]} />
    <header className="text-center">
      <div className="text-5xl" aria-hidden="true">{g.emoji}</div>
      <h1 className="mt-2 text-4xl sm:text-5xl">{title}</h1>
      <p className="mx-auto mt-2 max-w-2xl text-lg text-[var(--muted-foreground)]">{GRADE_COPY[n]}</p>
    </header>

    {topics.length > 0 ? <>
      <div className="mth-actions mt-5"><Link to={g.testPath} className="ln-btn go">📝 מבחן מסכם לכיתה {g.label}</Link></div>
      {groups.map(gr => <section key={gr.strand} className="mt-8" aria-labelledby={`s-${gr.strand}`}>
        <h2 id={`s-${gr.strand}`} className="mb-3 text-2xl font-black"><span aria-hidden="true">{gr.emoji} </span>{gr.label}</h2>
        <div className="grid gap-3 sm:grid-cols-2">{gr.topics.map(t => <Link key={t.slug} to={topicPath(t)} className="wobbly card-lift border-2 border-[var(--border)] bg-[var(--card)] sketch-shadow p-4 text-right mth-topic-card">
          <span className="text-3xl" aria-hidden="true">{t.emoji}</span>
          <span><span className="block text-lg font-black leading-snug">{t.title}</span><small className="block text-[var(--muted-foreground)]">{t.levels.join(' · ')}</small></span>
        </Link>)}</div>
      </section>)}
    </> : <p className="ln-box mt-6 text-center">הנושאים לכיתה {g.label} יעלו בקרוב. בינתיים אפשר לתרגל נושאים של כיתות אחרות.</p>}

    <nav className="mth-grade-nav mt-10" aria-label="כיתות סמוכות">
      {prev && <Link to={prev.path} className="ln-chip">→ כיתה {prev.label}</Link>}
      <Link to="/math" className="ln-chip">כל הכיתות</Link>
      {next && <Link to={next.path} className="ln-chip">כיתה {next.label} ←</Link>}
    </nav>

    <div className="mt-10"><SeoBody paragraphs={[
      `${GRADE_COPY[n]} כאן מרוכזים הנושאים של כיתה ${g.label} לפי תחומים, וכל נושא מוביל לעמוד עם הסבר קצר, דוגמה פתורה ותרגול בשלוש רמות קושי.`,
      `התרגילים נוצרים מחדש בכל פעם, כך שאפשר לחזור לאותו נושא שוב ושוב בלי לפגוש את אותם תרגילים. אחרי כל תשובה מופיע הסבר קצר, ובסוף אפשר לבדוק את עצמכם במבחן המסכם לכיתה ${g.label} או להדפיס דף עבודה עם דף תשובות.`,
    ]} faq={faq} related={[HUB, ...(prev ? [{ label: `מתמטיקה לכיתה ${prev.label}`, href: prev.path }] : []), ...(next ? [{ label: `מתמטיקה לכיתה ${next.label}`, href: next.path }] : []), { label: 'דפי עבודה בחשבון', href: '/printables/math-worksheets' }]} /></div>
  </div>
}

// ── /math/grade-N/:topicSlug ───────────────────────────────
export function MathTopic() {
  const { gradeSlug, topicSlug } = useParams()
  const n = parseGradeParam(gradeSlug)
  const topic = n ? findTopic(n, topicSlug) : null
  if (!topic) return <NotFound />
  return <TopicPage key={`${n}/${topicSlug}`} topic={topic} />
}

function TopicPage({ topic }) {
  const g = gradeInfo(topic.grade)
  const [level, setLevel] = useState(1)
  const [mode, setMode] = useState('practice')
  const [quiz, setQuiz] = useState(null) // { items, key }
  const [print, setPrint] = useState(null) // { items, seed }
  const startQuiz = () => setQuiz({ items: makeWorksheet(topic, level, 10, newSeed()), key: newSeed() })
  const openPrint = (lv = level) => setPrint({ items: makeWorksheet(topic, lv, 20, newSeed()), level: lv })
  const siblings = topicsFor(topic.grade).filter(t => t.slug !== topic.slug)
  const h1 = `${topic.title} — כיתה ${g.label}`
  const faq = [...topic.faq, { q: `איך מתרגלים ${topic.title} בכיתה ${g.label}?`, a: `בוחרים רמה (${topic.levels.map((l, i) => `${i + 1} — ${l}`).join('; ')}), פותרים תרגיל אחרי תרגיל ורואים הסבר אחרי כל תשובה. אפשר גם לעבור למצב מבחן של 10 שאלות או להדפיס דף עבודה של 20 תרגילים עם דף תשובות.` }]
  const schema = [faqSchema(faq), {
    '@context': 'https://schema.org',
    '@type': 'LearningResource',
    'name': h1,
    'description': topic.desc,
    'inLanguage': 'he',
    'educationalLevel': `כיתה ${g.label}`,
    'learningResourceType': ['תרגול', 'דף עבודה', 'מבחן'],
    'about': STRANDS[topic.strand]?.label,
    'isAccessibleForFree': true,
    'url': `https://ugabuga.co.il${topicPath(topic)}`,
  }]
  return <div className="mx-auto max-w-4xl px-4 py-8 buga-fade-in" dir="rtl">
    <SEO title={`${topic.title} לכיתה ${g.label} — הסבר, תרגול ודף עבודה`} description={topic.desc} path={topicPath(topic)} type="article" structuredData={schema} />
    <Breadcrumbs items={[HOME, HUB, gradeCrumb(g), { label: topic.title }]} />
    <header className="text-center">
      <div className="text-5xl" aria-hidden="true">{topic.emoji}</div>
      <h1 className="mt-2 text-3xl sm:text-5xl">{h1}</h1>
      <p className="mt-2 font-bold text-[var(--muted-foreground)]">{STRANDS[topic.strand]?.label} · {g.stageLabel}</p>
    </header>

    <section className="ln-box mth-explainer mt-6" aria-labelledby="exp-h">
      <h2 id="exp-h" className="text-2xl font-black">💡 מה צריך לדעת</h2>
      <MathText as="p" className="text-lg leading-relaxed">{topic.intro}</MathText>
      <ul className="mth-tips">{topic.tips.map((t, i) => <li key={i}><MathText>{t}</MathText></li>)}</ul>
      <div className="mth-example">
        <h3 className="text-lg font-black">דוגמה פתורה</h3>
        <MathText as="p" className="font-bold">{topic.example.q}</MathText>
        <ol>{topic.example.steps.map((s, i) => <li key={i}><MathText>{s}</MathText></li>)}</ol>
        <p className="m-0">✅ תשובה: <MathText>{topic.example.a}</MathText></p>
      </div>
    </section>

    <section className="no-print mt-6" aria-label="רמה ומצב">
      <div className="flex flex-wrap justify-center gap-2" role="group" aria-label="רמת קושי">
        {topic.levels.map((l, i) => <Chip key={i} on={level === i + 1} onClick={() => { setLevel(i + 1); setQuiz(null) }}>{['🟢', '🟡', '🔴'][i]} רמה {i + 1}: {l}</Chip>)}
      </div>
      <div className="mt-3 flex flex-wrap justify-center gap-2" role="group" aria-label="מצב">
        <Chip on={mode === 'practice'} onClick={() => setMode('practice')}>✏️ תרגול</Chip>
        <Chip on={mode === 'quiz'} onClick={() => setMode('quiz')}>📝 מבחן (10 שאלות)</Chip>
        <Chip on={false} onClick={() => openPrint()}>🖨️ דף עבודה להדפסה</Chip>
      </div>
    </section>

    <div className="mt-5">
      {mode === 'practice' && <Practice topic={topic} level={level} />}
      {mode === 'quiz' && (quiz
        ? <Quiz key={quiz.key} items={quiz.items} timer title={`מבחן: ${topic.title}`} onRestart={startQuiz} onPrint={() => setPrint({ items: quiz.items, level })} />
        : <div className="ln-box text-center space-y-3"><p className="m-0 text-lg">10 שאלות ברמה {level} ({topic.levels[level - 1]}). עונים על הכול — והבדיקה, הציון וההסברים מגיעים בסוף. השעון סופר את הזמן.</p><button type="button" className="ln-btn go" onClick={startQuiz}>▶ מתחילים מבחן</button></div>)}
    </div>

    {print && <PrintPreview title={`${topic.title} — כיתה ${g.label}`} onClose={() => setPrint(null)} onRefresh={() => openPrint(print.level)}>
      <PrintSheets title={`${topic.title} — כיתה ${g.label}`} sub={`רמה ${print.level}: ${topic.levels[print.level - 1]}`} items={print.items} />
    </PrintPreview>}

    <section className="no-print mt-10" aria-labelledby="more-h">
      <h2 id="more-h" className="mb-3 text-2xl font-black text-center">עוד נושאים לכיתה {g.label}</h2>
      <div className="flex flex-wrap justify-center gap-2">{siblings.map(t => <Link key={t.slug} to={topicPath(t)} className="ln-chip"><span aria-hidden="true">{t.emoji}</span> {t.title}</Link>)}</div>
      <p className="mt-4 text-center"><Link to={g.testPath} className="font-bold underline">📝 מבחן מסכם לכיתה {g.label}</Link> · <Link to={g.path} className="font-bold underline">כל הנושאים לכיתה {g.label}</Link></p>
    </section>

    <div className="mt-10"><SeoBody paragraphs={[
      `${topic.title} הוא אחד הנושאים במתמטיקה לכיתה ${g.label}, בתחום ${STRANDS[topic.strand]?.label || ''}. בעמוד הזה יש הסבר קצר, טיפים ודוגמה פתורה, ואחריהם תרגול בשלוש רמות: ${topic.levels.map((l, i) => `רמה ${i + 1} — ${l}`).join(', ')}.`,
      'כל תרגיל נוצר מחדש, ולכן אפשר להמשיך לתרגל כמה שרוצים. אחרי כל תשובה מופיעים בדיקה והסבר קצר; במצב מבחן הבדיקה מגיעה רק בסוף, עם ציון וסקירה של כל השאלות. לדף עבודה מודפס יש דף תשובות נפרד, כך שהילדים יכולים לבדוק את עצמם או שההורה או המורה יבדקו.',
    ]} faq={faq} related={[gradeCrumb(g), { label: `מבחן במתמטיקה לכיתה ${g.label}`, href: g.testPath }, HUB]} /></div>
  </div>
}

// ── /math/tests/grade-N ───────────────────────────────
export function MathTest() {
  const n = parseGradeParam(useParams().gradeSlug)
  if (!n || !topicsFor(n).length) return <NotFound />
  return <TestPage key={n} n={n} />
}

const TEST_LEVELS = [{ v: 0, label: '🎢 מעורב (מתחיל קל ומתקשה)' }, { v: 1, label: '🟢 בסיסי' }, { v: 2, label: '🟡 בינוני' }, { v: 3, label: '🔴 מתקדם' }]

function TestPage({ n }) {
  const g = gradeInfo(n)
  const topics = topicsFor(n)
  const [level, setLevel] = useState(0)
  const [count, setCount] = useState(10)
  const [timer, setTimer] = useState(true)
  const [quiz, setQuiz] = useState(null)
  const [print, setPrint] = useState(null)
  const start = () => setQuiz({ items: makeTest(n, count, newSeed(), level), key: newSeed() })
  const openPrint = (items = makeTest(n, count, newSeed(), level)) => setPrint({ items })
  const h1 = `מבחן במתמטיקה לכיתה ${g.label}`
  const lvLabel = TEST_LEVELS.find(l => l.v === level).label.replace(/^\S+ /, '')
  const faq = [
    { q: `מה כולל המבחן במתמטיקה לכיתה ${g.label}?`, a: `שאלות מכל ${topics.length} הנושאים של כיתה ${g.label}: ${listHe(topics.map(t => t.title))}. כל מבחן נוצר מחדש, כך שאפשר לעשות כמה מבחנים שונים.` },
    { q: 'איך מחושב הציון?', a: 'כל שאלה שווה אותו מספר נקודות. בסוף המבחן מקבלים את מספר התשובות הנכונות, ציון בין 0 ל-100 וסקירה של כל השאלות — עם התשובה הנכונה והסבר לכל טעות.' },
    { q: 'אפשר להדפיס את המבחן?', a: 'כן. לוחצים על "הדפסת מבחן" ומקבלים דף מבחן עם מקום לשם ולציון, ודף תשובות נפרד לבדיקה. בכל פעם נוצר מבחן חדש.' },
  ]
  return <div className="mx-auto max-w-4xl px-4 py-8 buga-fade-in" dir="rtl">
    <SEO title={`${h1} — מבחן אונליין והדפסה עם תשובות`} description={`${h1}: מבחן מסכם מכל הנושאים של כיתה ${g.label}, 10 או 20 שאלות, שלוש רמות, טיימר, ציון וסקירת טעויות — וגם מבחן להדפסה עם דף תשובות. חינם.`} path={g.testPath} structuredData={faqSchema(faq)} />
    <Breadcrumbs items={[HOME, HUB, gradeCrumb(g), { label: 'מבחן מסכם' }]} />
    <header className="text-center">
      <div className="text-5xl" aria-hidden="true">📝</div>
      <h1 className="mt-2 text-3xl sm:text-5xl">{h1}</h1>
      <p className="mx-auto mt-2 max-w-2xl text-lg text-[var(--muted-foreground)]">מבחן שמערבב שאלות מכל הנושאים של כיתה {g.label}. עונים על כל השאלות, ובסוף מקבלים ציון והסבר לכל טעות.</p>
    </header>

    {!quiz && <section className="ln-box mt-6 space-y-4 text-center" aria-label="הגדרות המבחן">
      <div><p className="font-bold m-0 mb-2">רמת קושי</p><div className="flex flex-wrap justify-center gap-2" role="group" aria-label="רמת קושי">{TEST_LEVELS.map(l => <Chip key={l.v} on={level === l.v} onClick={() => setLevel(l.v)}>{l.label}</Chip>)}</div></div>
      <div><p className="font-bold m-0 mb-2">מספר שאלות</p><div className="flex flex-wrap justify-center gap-2" role="group" aria-label="מספר שאלות">{[10, 20].map(c => <Chip key={c} on={count === c} onClick={() => setCount(c)}>{c} שאלות</Chip>)}<Chip on={timer} onClick={() => setTimer(!timer)}>⏱️ שעון {timer ? 'פועל' : 'כבוי'}</Chip></div></div>
      <div className="mth-actions"><button type="button" className="ln-btn go" onClick={start}>▶ מתחילים מבחן</button><button type="button" className="ln-btn alt" onClick={() => openPrint()}>🖨️ הדפסת מבחן</button></div>
    </section>}
    {quiz && <div className="mt-6">
      <Quiz key={quiz.key} items={quiz.items} timer={timer} title={h1} onRestart={() => setQuiz(null)} onPrint={() => openPrint(quiz.items)} />
      <p className="mt-3 text-center no-print"><button type="button" className="underline" onClick={() => setQuiz(null)}>יציאה מהמבחן</button></p>
    </div>}

    {print && <PrintPreview title={h1} onClose={() => setPrint(null)} onRefresh={() => openPrint()}>
      <PrintSheets title={h1} sub={`רמה: ${lvLabel} · ${print.items.length} שאלות`} items={print.items} />
    </PrintPreview>}

    <section className="no-print mt-10" aria-labelledby="topics-h">
      <h2 id="topics-h" className="mb-3 text-2xl font-black text-center">רוצים לתרגל נושא אחד?</h2>
      <div className="flex flex-wrap justify-center gap-2">{topics.map(t => <Link key={t.slug} to={topicPath(t)} className="ln-chip"><span aria-hidden="true">{t.emoji}</span> {t.title}</Link>)}</div>
    </section>

    <div className="mt-10"><SeoBody paragraphs={[
      `המבחן המסכם לכיתה ${g.label} בונה בכל פעם מבחן חדש משאלות בכל הנושאים של הכיתה, כך שכל נושא מופיע לפני שנושא כלשהו חוזר. ברמה המעורבת המבחן מתחיל בשאלות קלות ומתקשה בהדרגה, כמו מבחן בכיתה.`,
      'אפשר לעבור בין השאלות, לדלג ולחזור, ורק בלחיצה על "סיום ובדיקה" מתקבלים הציון, הזמן וסקירה מלאה. מבחן מודפס מגיע עם דף תשובות נפרד — נוח להורים שרוצים לבדוק, ולמורים שמחפשים מבחן חזרה.',
    ]} faq={faq} related={[gradeCrumb(g), HUB]} /></div>
  </div>
}
